### ISSUE TITLE
How to insert an ARRAY type?

### ISSUE THREAD

**Issue by eldilibra** [jmoiron/sqlx#106]
I've a struct like:

``` go
type Foo struct {
  //some other fields here
  Things []string `db:"things"`
}
```

When I run something like this through NamedQuery:

``` sql
INSERT INTO foos (things) VALUES (:things)
```

I get the following error message:
"sql: converting Exec argument #3's type: unsupported type []string, a slice"

My PostgreSQL db has that field set to an ARRAY (of type uuid, but that is besides the point)

Are we just not allowed to use ARRAYs under the hood with sqlx?

**Comment by fiatjaf** [comment]
For people wandering here, I think I should mention the `string_to_array(text, text [, text])` [Postgres array function](http://www.postgresql.org/docs/9.4/static/functions-array.html) which should make simpler (although a little hackier) to insert arrays.

**Comment by gravis** [comment]
Are you talking about this PR? https://github.com/lib/pq/pull/302
thanks

**Comment by winduptoy** [comment]
@jmoiron Care to post an example implementation for these? Would really help me out.

```
func (p *pgStringSlice) Scan(src interface{}) error { ... }
func (p *pgStringSlice) Value() (driver.Value, error) { ... }
```
