### ISSUE TITLE
types.JsonText extraneous whitespace in database.

### ISSUE THREAD

**Issue by itsjamie** [jmoiron/sqlx#108]
I can submit a pull-request for this type that uses json.Compact to remove any whitespace in the implementation of the Value() function.

However, I could understand if you would rather have users opt-in to this behaviour and do it themselves.

Let me know.

Thanks for the great library!

**Comment by jmoiron** [comment]
Though I think they are useful, `sqlx/types` are sort of half demonstrative as well.  I think this can be achieved pretty elegantly with embedding by any people who might want to do so:

```go
type CompactJson struct {
        types.JsonText
}

func (c CompactJson) Value() (driver.Value, error) {
        v, err := c.j.Value()
        if err != nil {
                return v, err
        }
        var buf bytes.Buffer
        err = json.Compact(&buf, v)
        return buf.Bytes(), err
}
```
