### ISSUE TITLE
Naming Conventions for foreign keys?

### ISSUE THREAD

**Issue by tschundeee** [jmoiron/sqlx#111]
Concerning naming conventions for databases: 

go vet suggests to have fields like UserID in a struct. 

In an mysql table I would prefer the name user_id. but for example sqlx wants you to use userid in order to correctly automap to UserID.
How do you call your foreign keys in databases and go structs?

I saw that there is `db:"user_id"` as annotation available.
Shouldn't sqlx be able to automatically map user_id in the db to UserID in a struct as they seem to be the convention for sql databases and golang?

Thx for clarification. Haven't found this in the docs.

**Comment by jmoiron** [comment]
You can add a name mapper to suit whatever needs you have.  For instance, if you want to turn CamelCase -> snake_case, you can write a function that does so and suits your needs and then:

```go
func camelToSnake(s string) string {
    // content..
}

db := db.MustConnect(...)
db.MapperFunc(camelToSnake)
```

This would change the default name mapping from `strings.ToLower`.  

Although I know such a function might be popular, it's actually somewhat complex to get right for everyone's needs.  How do you deal with multiple capital letters in a row, like `BlogURL`?  How do you deal with numbers?  Using `strings.ToLower` is incredibly straightforward and still matches many db schema.
