### ISSUE TITLE
Scanning nested structs

### ISSUE THREAD

**Issue by Acconut** [jmoiron/sqlx#112]
Assuming following setup:

```go
type Post struct{
     Id string `db:"post_id"`
     Title string
     Author *User
}

type User struct {
      Id string `db:"user_id"`
      Name string
}
```

and this SQL query:

```sql
SELECT posts.post_id, posts.title, users.user_id, users.name
FROM posts, users
WHERE posts.user_id = users.user_id
AND posts.post_id = 123
```

Am I able to scan this into a Post struct using `sqlx.DB.Get` or `sqlx.DB.Select`? I've tried to implement the `sql.Scanner` interface of both structs but I get an error saying `scannable dest type struct with >1 columns (2) in result`.

**Comment by jmoiron** [comment]
You should be able to embed the user in the Post struct anonymously:

```go
type Post struct {
    Id string `db:"post_id"`
    Title string
    User
}
```

Older versions descended down non-embedded structs but this was problematic and somewhat confusing.  I will try to work on the error message;  if `User` implements Scanner, it should be scannable, but you would not be able to scan two different columns into it.

**Comment by Acconut** [comment]
Thanks for this answer. Embedding a struct works but I now have to problem of name conflicts (exactly what the EmbedConflict test does).

I could implement Scanner and use [composite types](http://www.postgresql.org/docs/8.4/static/rowtypes.html) (I'm not sure whether this is standard SQL or just for PostgreSQL) to push multiple columns into one.

**Comment by jmoiron** [comment]
The example above should not have name conflicts.  You can still access the User Id like this:

```go
p := Post{..}
p.User.Id // <- legal
```

If you think of embedded structs as a tree of namespaces, similar to how scopes are, then lookups follow a breadth first rule, which is how Go's lookups work.  That's why you can have `EmbedConflict`;  in fact, the Go compiler does not allow ambiguous attribute accesses to compile, eg:

```go
type T1 struct {
    Id string
}
type T2 struct {
    Id string
}
type T3 struct {
    T1, T2
}

t := T3{}
t.Id  // <- compiler error
```

The compiler error actually happens on the *access*, so defining T3 without accessing Id from that level is legal.  Therefore, sqlx has to throw this error at runtime if it happens.

**Comment by Acconut** [comment]
When speaking about naming conflicts I was not referring to the names inside the Go structs. I have two or more tables which all have one column which share the same name. My current approach to work around this is using `AS` statements.

**Comment by rof20004** [comment]
@Acconut can you share a code example for this with AS statements?

**Comment by Acconut** [comment]
Sorry, @rof20004. This was more than three years ago, I don't have the code at my hands anymore

**Comment by rof20004** [comment]
@Acconut you don't use sqlx any more?

**Comment by Acconut** [comment]
No, I work on different things these days

**Comment by rof20004** [comment]
@Acconut Ok, thanks!
