### ISSUE TITLE
sqlx.In

### ISSUE THREAD

**Issue by jmoiron** [jmoiron/sqlx#123]
I want to try addressing one of the elephants in the room in `database/sql` land, which is dealing with IN type queries.

The problem arises with queries like this:

```sql
SELECT * FROM people WHERE id IN (1,2,3,4,5);
```

In code, you often have this scenario:

```go
ids := []int{}
for _, user := range userGroup {
    ids = append(ids, user.Id)
}
q := `SELECT * FROM people WHERE id IN (?)`
```

Now we have a problem;  the driver will not handle an `[]int{}` in the way we want here;  our query actually has to look like `.. WHERE id IN (?, ?, ...)`, with a number of bindVars equal to `len(ids)`.  This is incredibly cumbersome.

The proposed solution to this will work similarly to some of the internal-only named query support functions.  This will have the same limitations with its parsing as well:

* the `?` character will be used as the bindVar, *only*, regardless of database.
* all `?` characters are considered bindVars.  If you need to use a literal `?`, you cannot use this function

The new function will look like this:

```Go
func (d *DB) In(query string, args ...interface{}) (query string, args []interface{}) {
    // each ? corresponding to "slice kind" var gets expanded
}
```

And be used like this:

```Go
// generate an In query with appropriate args []interface{}
q, args := db.In("SELECT * FROM people WHERE id IN (?)", ids)
```

**Comment by tristanwietsma** [comment]
This would be appreciated. I've actually been handling this by expanding the named parameters and breaking the slice elements out and putting them in the map. Hacky, but effective. Little snippet....

```go
if reflect.TypeOf(val).Kind() == reflect.Slice {
	slc := reflect.ValueOf(val)
	subs := []string{}
	for i := 0; i < slc.Len(); i++ {
		element := fmt.Sprintf("%v", slc.Index(i).Interface())
		if !IsType(element, t) {
		        writeError(w, http.StatusBadRequest,
			"%v is invalid for type %v", val, t)
			return
		}
                newKey := fmt.Sprintf("%v%d", param, i)
			subs = append(subs, newKey)
			params[newKey] = element
		}
		replacement := ":" + strings.Join(subs, ", :")
		thisQuery = strings.Replace(thisQuery, ":"+param, replacement, -1)
        }
}
```

**Comment by jmoiron** [comment]
The current hangup is whether or not to include the binding in the call to `In`.  I like the interface defined above with `sqlx.In(q string, args ...interface{})`, but it won't know the driver type and it will mean the extra step of rebinding yourself each time.  Possible interfaces:

* `sqlx.In(q string, args ...interface{})` - does not do query param binding;  extra step for users of non-QUESTION bindvar databases
* `sqlx.In(b binder, q string, args ...interface{})` - exposes the Binder interface which might already be exposed, but it's not immediately clear what it is.
* `sqlx.DB.In(q string, args ...interface{})` - nicer interface, but it's actually a bit unclear why the `DB` is necessary to outsiders, and I'd probably have to add it to `Tx` as well for congruence.

Either binding is left to the caller:

```go
q, args := sqlx.In("select * from bar where x in (?)", someSlice)
q = db.Rebind(q)
```

Or an alternate `InBind` function is written that takes the binder.

Or it's just hung off the DB & Tx objects.

**Comment by chowey** [comment]
How would this support NamedExec?

I do an approach similar to @tristanwietsma that converts something like this:

```
SELECT * FROM people WHERE id IN (:id);
```

to something like this:

```
SELECT * FROM people WHERE id IN (:id, :id_1, :id_2, :id_3, :id_4);
```

which also requires that the `arg` parameter for NamedExec is a map and that I dynamically add `id_1`, `id_2`, etc. to the map.

Your current `sqlx.In` proposal seems like it would not work with a NamedExec. Or does NamedExec now use `sqlx.In` under-the-hood when it encounters a slice in its `arg` parameter?

**Comment by jmoiron** [comment]
That's a good question.

The current proposed solutions are to have `sqlx.In` be a separate manner of pre-processing a query/args list.  With `sqlx.BindNamed`, you can get from `(namedQuery string, arg interface{})` -> `(query string, args []interface{})` already, so from there you could use `sqlx.In` to get the real end result.

I did not think the implementation of `BindNamed` through, and because of that it's interface is a bit wonky from a user perspective.  It makes a bit more sense from a "I want people to be able to use sqlx to build their database libraries" perspective, but it's still not great.

Currently, it'd just be a small utility to combine them:

```go

func CompileNamedQuery(query string, arg interface{}) (string, []interface{}, error) {
    q, args, err := sqlx.BindNamed(sqlx.QUESTION, query, arg)
    if err != nil {
        return q, args, err
    }
    return sqlx.In(q, args...)
}
```

I could see myself changing the BindNamed interface in the future;  it exposes bindTypes which most people don't care about (again this was for library-writers not application-writers) and it isn't likely to be widely used.  It's also making me realize that all sqlx query parsing should just standardize on the simpler `question` bind type for composabilities sake and then let the user rebind at the end when they need to;  if `BindNamed` used the a binder to bind the query, and you passed it a postgresql connected DB object, you wouldn't be able to compose it with `In` anymore.

**Comment by jmoiron** [comment]
This has been released as `sqlx.In`
