### ISSUE TITLE
sqlx.Preparer and NamedStmt

### ISSUE THREAD

**Issue by james-lawrence** [jmoiron/sqlx#124]
Be nice if there was an equivalent sqlx.Preparer for NamedStmts and an interface that implemented both sqlx.Preparer and the sqlx.NamedPreparer. Which both sqlx.Tx and sqlx.DB implemented.

Helps with situations where you might want to build a service within a transaction.

example code:
```
func somefunc(db *sqlx.DB) {
  // ....
  if tx, err = db.Beginx(); err != nil {
    return
  }

  svc_a := NewSvcA(tx)
  svc_b := NewSvcB(tx)
  // could at this point pass the svc_a/svc_b to other functions that don't know
  // its running within a transaction and then perform rollbacks within this function
  // if something goes wrong. I've also had the svc_a/b implement an interface WithTx(tx *sqlx.Tx) SvcA
  // that convert the service into one running within a tx. which works for both sqlx.Stmt and sqlx.NamedStmt
  if err := svc_a.Create(input_a, &result_a); err != nil {
    goto done
  }
  
 err := svc_b.Create(input_b, &result_b)
done:
  if err == nil {
    tx.Commit()
  } else {
    tx.Rollback()
  }
 }
```
but sometimes I want them to be a standalone:
```
func somefunc(db *sqlx.DB) {
  // ...
  svc_a := NewSvcA(db)

  if err := svc_a.Create(input_a, &result_a); err != nil {
    goto done
  }

  // ...
}
```

Now granted doing it this way I lose some performance because I'm reparsing the statements each time. But even beyond same code of the use case, Tx/DB can be treated similarly in many cases where we don't care if its within a TX or not. (for example sqlx.Preparer) but not for named statements.

**Comment by jmoiron** [comment]
`DB` and `Tx` both implement the same signature for `PrepareNamed`.  If you require such an interface it's easy to define it:

```go
type preparer interface {
    PrepareNamed(query string) (*NamedStmt, error)
}
```

And then use this.
