### ISSUE TITLE
(type sql.Result has no field or method LastCreatedId)

### ISSUE THREAD

**Issue by nickckaye** [jmoiron/sqlx#126]
*I'm fairly new to Go, so forgive me if this is just an oversight. If I solve it, I'll close this issue.*

Given:
```
func (app *App) UserCreate() int {
  result := app.db.MustExec(`INSERT INTO user (created_at) VALUES (?)`,time.Now())
  return result.LastCreatedId()
}
```

Failing:
```
$ go test
./model.go:114: result.LastCreatedId undefined (type sql.Result has no field or method LastCreatedId)

Thoughts? Many thanks!

**Comment by jszwedko** [comment]
@nickckaye I think you are looking for http://golang.org/pkg/database/sql/driver/#RowsAffected.LastInsertId -- note that this isn't supported by all SQL drivers.

**Comment by nickckaye** [comment]
@jszwedko it's true!  The documentation at http://jmoiron.github.io/sqlx/#exec says `LastCreatedId` and I think maybe that's a typo? Or perhaps that's just trying to illustrate other possibilities?

**Comment by jszwedko** [comment]
@nickckaye yeah, that looks like a typo to me.

**Comment by kmatrah** [comment]
Hi all,
The method is `LastInsertId` not `LastInsertedId` :)
https://golang.org/pkg/database/sql/#Result
