### ISSUE TITLE
SliceScan returns []int8 instead of string

### ISSUE THREAD

**Issue by kokizzu** [jmoiron/sqlx#128]
I think it would be better to return `string` instead of `[]int8` when calling `SliceScan()` for string result
```
// rows is *sqlx.Rows from `SELECT anystring FROM anytable`
ba, ok := rows.SliceScan()
ba[0] // is []int8
```

Database: PostgreSQL 9.4

**Comment by jmoiron** [comment]
This is how the driver works when you scan to `interface{}`;  it just scans a `[]byte`.  There's not a ton that could be done.  You can write your own filter which takes a `[]interface{}` and returns a new one whose `[]byte` have been converted to `string`.  It will look something like:

```go
func stringFilter(src []interface{}) []interface{} {
    dst := make([]interface{}, 0, len(src))
    for _, d := range src {
        b, ok := d.([]byte)
        if ok {
            dst = append(dst, string(b))
        } else {
            dst = append(dst, d)
        }
    }
    return dst
} 
```

**Comment by kokizzu** [comment]
I'm sorry, I forgot to close this issue, I misread the type back then, it's `uint8` instead of `int8`, I'm really sorry to take your time to check this issue.

**Comment by kokizzu** [comment]
and `[]uint8` easily can be converted to `string` so this no longer an issue.

**Comment by jmoiron** [comment]
No problem :)  I'm glad you figured it out.
