### ISSUE TITLE
bulk insert

### ISSUE THREAD

**Issue by areski** [jmoiron/sqlx#134]
I would appreciate any hints how to perform a bulk/batch insert.
I ve been looking at the test suit and I could not figure out how.

**Comment by jmoiron** [comment]
Do you want to do a parameterized bulk insert?  Eg:

```sql
INSERT INTO foo (a,b,c) VALUES (?, ?, ?), (?, ?, ?), ...;
```

If this is the case, sqlx does not provide any helpers for this, although if you are using a db that uses $1, $2, ... bindvars instead of the ? bindvar, you can build it with `?` (which will be easier) and then rebind it.

**Comment by areski** [comment]
I'm actually using `NamedExec`, my insert look like this:

    sqlQuery := "INSERT INTO mytable (field1, field2) VALUES (:field1, :field2)"
    res, err = tx.NamedExec(sqlQuery, vmap)

Is there a way to exec a Dry run wtih `NamedExec`, in order to copy the SQL in a buffer and then Exec all the insert in one call?

**Comment by jmoiron** [comment]
NamedExec and `BindNamed` have to take the names and convert them into a `[]interface{}` for execution with Query.  There's no way currently to do this in bulk, you have to call it each time.  This, for instance, is not handled:

```go
type thing struct { f1, f2 string }
var things []thing{...}
Query(`INSERT INTO mytable (field1, field2) VALUES (:f1, :f2), (:f2, :f2)`, things)
```

**Comment by areski** [comment]
Okey that's a pity. I will close the issue, feel free to reopen if needed.

**Comment by dcormier** [comment]
I would love to see this work, especially since [it can be done](https://stackoverflow.com/a/25192138/297468) with [DB.Exec](https://godoc.org/database/sql#DB.Exec) from the stdlib sql/database package.

**Comment by hrugani** [comment]
This would be a good improvement. I also need something like that.  I would appreciate one day have this feature at hand.

**Comment by ijhuang** [comment]
Would also like to see a helper for bulk inserts!

**Comment by cgebe** [comment]
duplicate https://github.com/jmoiron/sqlx/issues/238
already fixed in https://github.com/hmgle/sqlx/commit/018bd2dc4495148c6bc575e693573ea68c9ad506

Could you pull these changes?

**Comment by dcormier** [comment]
There's even an open PR to resolve this. #285.

**Comment by wubin1989** [comment]
There is a bug when there is on duplicate key update statement.
```
INSERT INTO `cloudx_wenjuan_luck`.`luckg_cross_sig`
(
`id`,
`survey_id`,
`bucket_key`,
`doc_count`,
`percent`,
`answer_total`,
`delete_at`)
VALUES (
        ?,
        ?,
        ?,
        ?,
        ?,
        ?,
        ?) ON DUPLICATE KEY
UPDATE
		`survey_id`=VALUES(survey_id),
		`bucket_key`=VALUES(bucket_key),
		`doc_count`=VALUES(doc_count),
		`percent`=VALUES(percent),
		`answer_total`=VALUES(answer_total),
		`delete_at`=VALUES(delete_at),(delete_at),(delete_at),(delete_at),(delete_at),(delete_at),(delete_at),(delete_at),(delete_at),(delete_at),(delete_at),(delete_at),(delete_at),(delete_at),(delete_at),(delete_at),(delete_at),(delete_at),(delete_at),(delete_at),(delete_at),(delete_at),(delete_at),(delete_at)
```

**Comment by brian-lai** [comment]
> There is a bug when insert multiple rows on duplicate key update.
> 
> ```
> INSERT INTO `cloudx_wenjuan_luck`.`luckg_cross_sig`
> (
> `id`,
> `survey_id`,
> `bucket_key`,
> `doc_count`,
> `percent`,
> `answer_total`,
> `delete_at`)
> VALUES (
>         ?,
>         ?,
>         ?,
>         ?,
>         ?,
>         ?,
>         ?) ON DUPLICATE KEY
> UPDATE
> 		`survey_id`=VALUES(survey_id),
> 		`bucket_key`=VALUES(bucket_key),
> 		`doc_count`=VALUES(doc_count),
> 		`percent`=VALUES(percent),
> 		`answer_total`=VALUES(answer_total),
> 		`delete_at`=VALUES(delete_at),(delete_at),(delete_at),(delete_at),(delete_at),(delete_at),(delete_at),(delete_at),(delete_at),(delete_at),(delete_at),(delete_at),(delete_at),(delete_at),(delete_at),(delete_at),(delete_at),(delete_at),(delete_at),(delete_at),(delete_at),(delete_at),(delete_at),(delete_at)
> ```

Does anyone know if there is a new ticket to address this bug for bulk upserts?
