### ISSUE TITLE
LIKE queries using %

### ISSUE THREAD

**Issue by ghigt** [jmoiron/sqlx#138]
Hi,

Is there a good way to build queries with `LIKE` and `%`?
I would like to do something like this:
```go
db.Select(&pp, "SELECT * FROM places WHERE LOWER(country) LIKE %?%", search)
```
I know I can concatenate `%` with `search` outside of the query, but I just ask if there is something better.

**Comment by jmoiron** [comment]
Hello,

You can embed the `%` in your query param, eg:

```
db.Select(&pp, "SELECT * FROM places WHERE lower(country) LIKE ?", "%"+search+"%"))
```

This should still be safe from injection attacks.

**Comment by pphowakande** [comment]
I am not getting any results with below code neither I am getting any error
Any idea ?



const selectAllByQuery = "SELECT * from groups WHERE lower(name) LIKE :name order by name asc"
q, err := dbc.PrepareNamed(selectAllByQury)
	if err != nil {
		return nil, err
	}
	fmt.Println("q : ", q)
query ="test"
	query = strings.ToLower(query)
	searchQry := "'%" + query + "%'"
	fmt.Println("search query :  ", searchQry)
	args := map[string]interface{}{
		"name": searchQry,
	}
	fmt.Println("args : ", args)
	err = q.Select(&gs, args)
	fmt.Println("gs : ", gs)
	if err != nil {
		return nil, err
	}
