### ISSUE TITLE
Disable "missing destination name" error

### ISSUE THREAD

**Issue by callumj** [jmoiron/sqlx#143]
Is there an option to disable the "missing destination name" error returned when columns exist in the table but not in the model?

This makes it somewhat frustrating during development if you switch branches (and are then forced to roll back migrations) or even worse in production if you keep temporary columns around which could then bring down your application.

**Comment by callumj** [comment]
Any thoughts on this?

**Comment by jmoiron** [comment]
Sorry, I missed this notification. 

See  http://godoc.org/github.com/jmoiron/sqlx#DB.Unsafe

**Comment by lazyfingers** [comment]
please, omit the fields that are not present in the given struct, this would be a huge bonus.
