### ISSUE TITLE
mapping rows to nested structs/slices

### ISSUE THREAD

**Issue by ilgooz** [jmoiron/sqlx#149]
I have a struct like this:

```go
type User Struct {
  Id           int64
  Name    string
  Projects []Project  // many to many
  Emails   []Email      // one to many
  Address Address // one to one
}
```

I want to be able to scan my rows into this kinda structs. As you already can guess there I'm performing joined queries to get needed rows. There is such a tool like [sqlstruct] (https://github.com/kisielk/sqlstruct) but it doesn't support injecting structs/slices into parent structs/slices, you have to make this manually. Should or can we provide this feature for the sake of keeping main application logic simple?

**Comment by jmoiron** [comment]
There isn't really a great way to do this without foreknowledge of the schema, which sqlx does not and will never have.

For one to one, you can embed the struct directly, and I have some plans for some tools to make this a little easier as part of #131 

For one to many or many to many you have to identify that a particular row is represents the "same" item as another row.  Libraries that do this have to know what your primary keys are for each joined table for you to be able to establish this, I just don't see that happening.

Feel free to re-open this if you have a technical proposal for a change that you think could achieve this or meet somewhere halfway.  Thanks!

**Comment by csimplestring** [comment]
Recently I notice a java library can handle nested List (one-2-many, many-2-many): http://simpleflatmapper.org/ 

If we can do this in Go, that will be awesome.
