### ISSUE TITLE
Error with order by ASC or DESC

### ISSUE THREAD

**Issue by mewben** [jmoiron/sqlx#153]
I'm using postgresql and I have this code:
```
err := db.Select(&slicemembers, "SELECT * FROM place ORDER BY telcode $1", "DESC")
```

But it throws this error: 
```
{
  "Error": "pq: syntax error at or near \"$1\""
}
```

Is this not possible? Please help.

**Comment by elithrar** [comment]
You can't provide a keyword (like ASC or DESC) as a query parameter. You'll need to either have two query strings, or (safely) concatenate based on another param - e.g.

``
func GetPlaces(asc bool) ([]*Places, error) {
var order string
if asc == true {
    order = "ASC"
else {
    order = "DESC"
}

query := fmt.Sprintf("SELECT * FROM place ORDER BY telcode %s", order)
err := db.Select(&slicemembers, query)
```

By only accepting a fixed set of strings (`DESC` or `ASC`) you can compose the query manually and also avoid the possibility of an arbitrary or invalid string getting involved.

**Comment by jmoiron** [comment]
As Matt said you can only use replacement syntax for query parameters.  SQL syntax and column/table names won't work.  This is just part of the way that prepared queries work on all systems.

**Comment by mewben** [comment]
I see.. Thank you very much...
