### ISSUE TITLE
QueryRowx, UPDATE and RETURNING

### ISSUE THREAD

**Issue by davisford** [jmoiron/sqlx#155]
Should this work with PostgreSQL?

```go
sql := `UPDATE orgs SET name = $1 WHERE id = $2 RETURNING *`
err := db.QueryRowx(sql, org.Name, org.ID).StructScan(org)
// returns error: sql: no rows in result set
```

**Comment by davisford** [comment]
I should add that sql executes fine in `psql` for my database.  I'd like to do an update+select, so I can marshall the full, changed struct back up the stack, and not have golang default values.  

Aside from doing an update, and then going back again to select -- which seems cumbersome and unnecessary...this seems like it should work?

**Comment by davisford** [comment]
Ah, nvm....found the issue....long day.

**Comment by potatogopher** [comment]
@davisford What was your issue?

**Comment by jsteenb2** [comment]
@davisford what was the issue? I'm having similar issues and its also been a very long day lol

**Comment by dcormier** [comment]
I, too, wish I knew what the solution was.
