### ISSUE TITLE
named params, pattern matching and preventing SQLi

### ISSUE THREAD

**Issue by davisford** [jmoiron/sqlx#167]
Hi @jmoiron, consider the following WHERE clause: `WHERE email ILIKE '%bar.co%'` -- this is just a contrived example, but I'd like to provide general search capability on most of the columns in several tables without exposing myself to SQLi.  

So, the goal would be to used named params -- seems easier than bound `$` params to code, and it gets converted to that anyway it seems, for postgres.

I'm trying something like the following, all the `%c` injection here is to deal with golang fmt not trying to parse those special characters while inserting the others.

```go
params := map[string]interface{}{}
// etc...generating rest of statement
var col = "email"
var colval = "email_val"
clause := fmt.Sprintf(" :%s ILIKE '%c%c%s%c'", col, '%', ':', colval, '%')

params[col] = col
params[colval] = colval
log.Debug(sql)
log.Debug(db.BindNamed(sql, params)
nstmt, err := db.PrepareNamed(sql)
if err != nil {
   log.Error(err)
}
```

This is resulting in the following printed lines

```
* named param: WHERE  :email ILIKE '%:email_val%'  
* bound param: WHERE  $1 ILIKE '%$2%'
```

The latter statement is the printout from `BindNamed` log statement above, but trying to generate the named statement directly after produces the following error: `pq: could not determine data type of parameter $2`

So, seems like it wants a cast, but that's not so seemingly easy to do here.

`clause := fmt.Sprintf(" :%s ILIKE '%c%c%s%c'::text", col, '%', ':', colval, '%')` generates 

* named param: `WHERE  :first_name ILIKE '%:first_name_val%'::text` 
* bound param: `WHERE  $1 ILIKE '%$2%':text`
(note it ate up one of the `:` in the cast parsing named params.  It also won't parse.

Tried `fmt.Sprintf(" :%s ILIKE text('%c%c%s%c')", col, '%', ':', colval, '%')` but that generates:

* named param `WHERE  :first_name ILIKE text('%:first_name_val%')`
* bound param `WHERE  $1 ILIKE text('%$2%')`
which *seems* like it should work, but alas it complains: `pq: could not determine data type of parameter $2`

Any ideas on a better approach here?

**Comment by davisford** [comment]
Made some progress... so this seems to parse OK -- for named or bound params, I guess they need to standalone, and can't really exist as part of the pattern matching text.  The pattern matching text has to be constructed all up front and injected by itself:

```
var col = "email"
var colsearch = "'%b.co%'"
clause = fmt.Sprintf(" :%s ILIKE :%s", col, colsearch)
```

Generates:

* named param: `WHERE  :email ILIKE :email_search`
* bound param: `WHERE  $1 ILIKE $2` with args: `["email", "'%b.co%'"]` 

This is as expected, and the query executes without error.  The problem is it doesn't return any results and it should.  When I execute it in 0xDBE with same named params and values, it returns 3 results as expected.  My next step, I guess is to dial up postgres logging so I can see what is actually being sent to the database and why it doesn't seem to work.

**Comment by HeyImAlex** [comment]
Not sure if I fully understand, but:

> bound param: `WHERE $1 ILIKE $2 with args: ["email", "'%b.co%'"]`

Looks like the problem? The bound parameters are safe from injection already, so the single quotes around the `:email_search` string are actually being used in the query: it's looking for a string that starts with a single quote, ends with a single quote, and has `b.co` in the middle.

**Comment by davisford** [comment]
I don't remember the exact details now b/c it has been a while, but I believe you're right.  Closing...
