### ISSUE TITLE
StructScanning a Postgres table with json and non json columns

### ISSUE THREAD

**Issue by jotto** [jmoiron/sqlx#171]
**With a DDL and a Person type like this:**
```go

var schema = `
CREATE TABLE person (
    id text,
    fields jsonb DEFAULT '{}'
);`

type Person struct {
	Id		string `json:"id"`
	Name    string `json:"name"`
	Address string `json:"address"`
}
```

**Is there a way to struct scan a struct with an embedded type that maps to a json field?**

```go
type PersonSql struct {
	Id		string `db:"id"`
	Person	`db:"fields"`
}

personSql := PersonSql{}
db.Get(&personSql, "select * from person limit 1")
```

**or at this point does it make more sense just to use `database/sql` with an implementation of the Scanner interface:**

```go
func (p *Person) Scan(src interface{}) error {
  if data, ok := src.([]byte); ok {
    return json.Unmarshal(data, &p)
  }
  return nil
}
db.QueryRow("select id, fields from profiles limit 1").Scan(&person.Id, &person)
```

**Comment by davisford** [comment]
I've got the same question -- have you resolved this?  I'd like to do something like this:

```sql
CREATE TABLE persons(
  name varchar(25),
  settings_a varchar(25),
  settings_b varchar(25)
);

CREATE TABLE things(
  name varchar(25),
  settings_a varchar(25),
  settings_b varchar(25)
);
```

```go
type Settings struct {
  SettingsA string `json:"settings_a" db:"settings_b"`
  SettingsB string `json:"settings_b" db:"settings_a"`
}

type Person struct {
   Name string `json:"name" db:"name"`
   Settings Settings `json:"settings"`
}

type Thing struct {
  Name string `json:"name" db:"name"`
  Settings Settings `json:"settings"`
}
```

Right now, if I try something like this:

```go
var person Person
if err := db.QueryRowx(`INSERT INTO persons(name, settings_a, settings_b) VALUES($1, $2, $3) RETURNING *`, "name", "a", "b").StructScan(&person); err != nil {
   log.Error(err)
}
// errors out with "missing destination name settings_a"
```

How, can I get `StructScan` to understand it should target the embedded property with name `Settings`.  I know if I embed it directly in the struct it will work, but I'd like to have the named wrapper.

**Comment by jmoiron** [comment]
The scanner interface is likely the only way to go.  sqlx only knows about named columns it gets off of the result rows;  it doesn't know anything about structures internal to whatever that might be (eg json/jsonb);  it's the job of the destination type to figure out what to do with the data being `Scan`ned into it.

**Comment by jmoiron** [comment]
@davisford It should know to target the embedded fields if you embed the type:

```go
type Thing struct {
    Name string `json:"name" db:"name"`
    Settings `json:"settings"`
}
```

**Comment by davisford** [comment]
yup, all cool now - thanks!

**Comment by jotto** [comment]
@jmoiron thank you for the response and thank you for the great project!
