### ISSUE TITLE
is it impossible to implement this kind of code in sqlx?

### ISSUE THREAD

**Issue by goldalworming** [jmoiron/sqlx#175]
Is it impossible to create this kind of insert query?
        b := [5]string{"testing", "xyz@gmail.com", "12345", "test", "london"}
        qry := `" insert into customers_php (name, email, phone, address,city) values ?`
 
        // execute a query on the server
        result, err := db.Exec(qry,b)

**Comment by jmoiron** [comment]
You can do it like this:

```go
b := []string{"testing", "...", ...}
q := `insert into customers_php (name, email, phone, address, city) values (?, ?, ?, ?, ?)`
result, err := db.Exec(query, b...)
```

You can write a utility function to generate the `?, ...` list and use string formatting to generate that if it becomes a problem.  Take note of the [bindvars section](http://jmoiron.github.io/sqlx/#bindvars) in the sqlx documentation as well.

**Comment by goldalworming** [comment]
thank you

**Comment by goldalworming** [comment]
I think you should add it in documentation to show  the possibilities
