### ISSUE TITLE
should I worried about  mutex  in Mapscan? 

### ISSUE THREAD

**Issue by goldalworming** [jmoiron/sqlx#176]
should I worried about map mutex when use row. Mapscan?
 
rows, err := db.Queryx("SELECT * FROM place")
for rows.Next() {
    results := make(map[string]interface{})
    err = rows.MapScan(results)
}

since map  need rwmutex to use in concurrency
 https://blog.golang.org/go-maps-in-action

**Comment by elithrar** [comment]
If the map is local to that goroutine (it probably will be) you won't need
a mutex - the only thing writing to the map should be the `MapScan` method.

**Comment by goldalworming** [comment]
so the problem appear when I create map in main the written by goroutines so I need mutex.  map inside goroutines is no problem?

**Comment by elithrar** [comment]
Correct. If you're sharing a map around your program - and have multiple
writers - you must use a mutex (else you will suffer problems).

If you have a HTTP handler that calls a database function, and the function
creates (and returns) a map of the results, that's fine.

**Comment by goldalworming** [comment]
great! thanks a lot

**Comment by jmoiron** [comment]
You only have problems when accessing the same data from different goroutines.   I also suggest trying out the race detector.

**Comment by goldalworming** [comment]
thank you
