### ISSUE TITLE
Using sql.NullInt64 in structs and then passing the struct as argument for prepared statement.

### ISSUE THREAD

**Issue by alexanderbaran** [jmoiron/sqlx#177]
Is it possible to use the sql.NullInt64 types in structs and then pass in the whole struct as you would do normally when working with prepared statements?

**Comment by jmoiron** [comment]
Can you describe what you want to do with a short code snippet?

**Comment by AdrianLungu** [comment]
Hello, sorry for re-opening this but I think I've ran into the thing he was mentioning.

Let's take this struct as an example:

```
type Admin struct {
    Id int `json:"id" db:"id"`
    Privilege sql.NullInt64 `json:"privilege" db:"privilege"`
}
```

Now, if I'm trying to do a NamedExec like the following:

`db.NamedExec('UPDATE admins SET privilege=:privilege WHERE id=:id', entity)
`

It seems the _privilege_ ends up being _null_ even though the NullInt64 has value.
