### ISSUE TITLE
Problem with a simple select/get

### ISSUE THREAD

**Issue by prsolucoes** [jmoiron/sqlx#183]
Hi,

Im using sqlx now, but i have problems on my first select/get.

```golang
type Device struct {
	Id int64 `db:"id"`
}

var device = Device{}
err := sqlx.Get(&device, "SELECT id FROM device WHERE imei = :imei LIMIT 1", imei)
```

What is wrong with it?

**Comment by elithrar** [comment]
`err := sqlx.Get(&device, "SELECT id FROM device WHERE imei = :imei LIMIT 1", imei)`

Hi @prsolucoes—is this your *actual* code? Where are you initialising your database pool? It should be something like `var db *sqlx.DB` as a package global (as the simplest implementation).

Calling `sqlx.Get` directly won't work as there's no database connection to use.

**Comment by prsolucoes** [comment]
I know. This is only the problem part.

```golang
var DB *sqlx.DB

type Device struct {
	Id int64 `db:"id"`
}

func ConnectToDatabase() {
	var err error

	DB, err = sqlx.Connect("mysql", "uuu:ppp@(localhost:3306)/ddd?charset=utf8")
	if err != nil {
		Log("Erro while connect to database: " + err.Error())
		os.Exit(1)
	}
}
```

**Comment by elithrar** [comment]
What error messages are you getting? Are you getting anything back? A panic? 

Your actual SQL query doesn't look problematic (I assume that query works via psql).

**Comment by prsolucoes** [comment]
Ops, sorry man. I forgot put the error:

```
./main.go:243: cannot use &device (type *Device) as type sqlx.Queryer in argument to sqlx.Get:
	*Device does not implement sqlx.Queryer (missing Query method)
```

Sorry, my fault :(

**Comment by elithrar** [comment]
This is because you're calling `sqlx.Get` (https://godoc.org/github.com/jmoiron/sqlx#Get) and not `db.Get` (https://godoc.org/github.com/jmoiron/sqlx#DB.Get).

`sqlx.Get` expects a [`Queryer`](https://godoc.org/github.com/jmoiron/sqlx#Queryer) as the first argument, not a type to marshal the query results into.

Change your code to `err := db.Get(&device, "SELECT id FROM device WHERE imei = :imei LIMIT 1", imei)` will work (as per my first comment!) :+1:

**Comment by prsolucoes** [comment]
Ok. Near to work.

Now the Device object is not filled if code is:

```golang
var device = Device{}
err := DB.Get(&device, "SELECT id FROM device WHERE imei = $1 LIMIT 1", imei)
```

But filled if is:

```golang
var device = Device{}
err := DB.Get(&device, "SELECT id FROM device WHERE imei = 'TEST' LIMIT 1")
```

How i can correctly pass named query to Get?

**Comment by prsolucoes** [comment]
Can you help me?

**Comment by elithrar** [comment]
Log the value of `imei` before your query - e.g.

```go
log.Printf("imei before: %v", imei)
err := DB.Get(&device, "SELECT id FROM device WHERE imei = $1 LIMIT 1", imei)
log.Printf("imei after: %v", imei)
```

Also use the `psql` command line client for PostgreSQL to run your query against whichever IMEI you're checking against to 100% confirm that that IMEI exists.

**Comment by prsolucoes** [comment]
Yes, imei exsts. I run the query on datadase. Imei is a fixed strings that i sent to app. Now its only a test.

**Comment by prsolucoes** [comment]
Im using mysql.

```golang
imei = "TEST"
err := DB.Get(&device, "SELECT id FROM device WHERE imei = $1 LIMIT 1", imei)
```

![screenshot 2015-11-01 15 03 56](https://cloud.githubusercontent.com/assets/395096/10870120/cfc5fad6-80a9-11e5-907b-875e82afbdd8.png)

**Comment by prsolucoes** [comment]
I gave up. Now it is working with pure sql/database. Thanks.

**Comment by elithrar** [comment]
MySQL? Use ? instead of $1 / $2 / etc. I had assumed you were using the
right placeholder type for your database.

**Comment by jmoiron** [comment]
Even if you decide not to use sqlx, please read the [sqlx documentation](http://jmoiron.github.io/sqlx) as it contains a lot of general information that is useful to most users of database/sql.  It would have cleared up your bindvar issue.
