### ISSUE TITLE
sqlx.Named disappeared 

### ISSUE THREAD

**Issue by nizsheanez** [jmoiron/sqlx#186]
In last example of http://jmoiron.github.io/sqlx/#namedParams i see how to use named parameters for IN() condition. 
But i can't find this method.
Also can't find any tests for IN() condition

**Comment by elithrar** [comment]
It definitely exists: https://godoc.org/github.com/jmoiron/sqlx#Named - https://github.com/jmoiron/sqlx/blob/master/named.go#L295-L300

**Comment by nizsheanez** [comment]
Somehow VendorExperiment was enabled and confused me. Thanks!
