### ISSUE TITLE
DB.Select not querying correctly, no errors, postgres

### ISSUE THREAD

**Issue by naysayer** [jmoiron/sqlx#190]
I have the following function, bare with me as I know it's kind of a mess, please note it is a work in progress. Additionally, the query I am attempting to execute has been a brain teaser to say the least:

**The function:**
```
func OptimizedKeywordPagesBYKeywords(DB *sqlx.DB, PageableId, auditId int, PageableType, keyword, source string) ([]page.AudPage, error) {
	auditIdString := strconv.Itoa(auditId)
	PageableIdString := strconv.Itoa(PageableId)

	base := `SELECT "pages".* FROM "pages" 
	INNER JOIN "keyword_pages" ON "keyword_pages"."page_id" = "pages"."id" 
	INNER JOIN "keyword_statistics" ON "keyword_statistics"."id" = "keyword_pages"."keyword_statistic_id" 
	INNER JOIN "keyword_frequencies" ON "keyword_frequencies"."keyword_statistic_id" = "keyword_statistics"."id" 
		WHERE ((pageable_id = '%s' AND pageable_type = '%s') 
		AND (meta_description ~* '%s\M' or title ~* '%s\M' or h1_1 ~* '%s\M' or h2_1 ~* '%s\M' or h2_2 ~* '%s\M' or path ~* '%s\M' or content ~* '%s\M')) 
		AND "keyword_pages"."source" = '%s' 
		AND "keyword_pages"."optimized" = 't' 
		AND "keyword_frequencies"."audit_id" = '%s' 
			GROUP BY pages.id`

	query := fmt.Sprintf(base, PageableIdString, PageableType, keyword, keyword, keyword, keyword, keyword, keyword, keyword, source, auditIdString)

	var pages []page.AudPage

	err := DB.Select(&pages, query)

	if err != nil {
		return pages, err
	}

	return pages, nil
}
```

**The problem:**
- This query should be returning at least 1 row, it does so but not while using sqlx within go. 
- I know for a fact this query works, as I wrote it within pgAdmin3. 
- I have also logged the output the result of the query variable, and the query runs as expected, again this was using pgAdmin3. 
- The Select function returns no error
- I have scanned over the docs and attempted to google the issue with no avail

**Using:**
- Postgres: 9.4.1
- Go: 1.5

**Additional information:**
- message from running the query in pgAdmin3
```
Total query runtime: 33 ms.
1 row retrieved.
```
Please let me know if there is a portion of the documentation I have missed, or another function within sqlx I should be using rather than select, or if any additional information is required from me.

**Comment by trevorprater** [comment]
Does it return zero results or just hang when calling from sqlx?

**Comment by naysayer** [comment]
@trevorprater it returns 0 results.

**Comment by jmoiron** [comment]
If you are only expecting one row you can use `Get` for some better "one or none" semantics wrt error handling.

As for the query not working, can you try just using `db.Query()` on it and see if that fails as well?  This will be using the underlying `database/sql` implementation and if that fails then there is probably some kind of subtle issue with the query like quoting.

**Comment by naysayer** [comment]
@jmoiron In this case `Get` will not work as it can return any number of records. 

Additionally I attempted to use `db.Query()` per your suggestion, it did not work, It returned the same result which was nothing. (Keep in mind the same query does in fact work when using something like pgAdmin 3)

I will attempt to edit the query as related to quoting as you mentioned and will report back any findings. thanks.

**Comment by jmoiron** [comment]
@naysayer any updates on this?

**Comment by naysayer** [comment]
@jmoiron The schema for the application that yielded this issue allowed us to write the query in a different manor. I have not found a solution to this, so I will close the issue for now.
