### ISSUE TITLE
The problem of "Too many connections" with the driver MySQL

### ISSUE THREAD

**Issue by ftomza** [jmoiron/sqlx#195]
We have a single connection to the database server

```Go
app.DB, err = sqlx.Open ("mysql", "root:root@tcp(localhost:3306)/db")
app.DB.SetMaxIdleConns (2)
app.DB.SetMaxOpenConns (20)
```

If you execute `Get` method

```Go
err: = app.DB.Get (&r, query, id)
```

That's all good.

But when the method executes `Query`

```Go
_, err: = app.DB.Query (query, id)
```

Then the amount is reduced every time you call this method, and as a result the program hangs.

At the same time, in the north of database connections 20 "hanging" like sleeping

**Comment by jmoiron** [comment]
Get automatically executes the query and then returns the connection to [the connection pool](http://jmoiron.github.io/sqlx/#connectionPool).  Query does not;  the caller is responsible to either fully iterate or close the resultant `rows` object in order to return it.

**Comment by zylixn** [comment]
rows.Close()可以释放
