### ISSUE TITLE
How to unpack err returned from QueryRow on INSERT/DELETE 

### ISSUE THREAD

**Issue by pandex** [jmoiron/sqlx#199]
I'm connecting to POSTGRES to INSERT and DELETE some simple stuff, like so:
    
    var cat string = "orange"
    err := db.QueryRowx("DELETE FROM myTable WHERE x=$1;", cat)
    if err != nil { 
        log.Println("ERROR:", err)
        return
    }

this will log when record (x="orange") could NOT be found: 

    &{<nil> false 0xc208052420 0xc20803ba40}

but will also log when record (x="orange") was found AND deleted successfully:

    &{<nil> 0xc208052420}

IOW, **if err != nil** seems to run regardless.

I'm a little unsure about what **db.QueryRowx** returns here. How exactly do I unpack "err" above to see what happened, whether it's INSERT, DELETE or any other POSTGRES operation ?

**Comment by mayhewj** [comment]
`QueryRowx` returns a `*Row`, not an `error`.

You should be using the `Exec` functions for inserts and deletes which returns a [`Result`](https://godoc.org/database/sql#Result).

**Comment by pandex** [comment]
Got it, thanks mayhewj.
