### ISSUE TITLE
LastInsertId and SQLite3

### ISSUE THREAD

**Issue by sim4life** [jmoiron/sqlx#200]
In SQLite3, I'm using the technique provided at the end of Issue #154:

```
stmt, err := db.PrepareNamed("INSERT INTO person (name, email) VALUES (:name, :email) RETURNING id")
// check error
var id int
err = stmt.Get(&id, arg)
```

 but it says: 
`near "RETURNING": syntax error`

and if I remove the `RETURNING id` clause from the end of Insert sql statement then I get 0 as the id.
Any suggestions?

**Comment by jmoiron** [comment]
RETURNING is for postgresql.  For sqlite3, you should be able to use `stmt.Exec` and `Result.LastInsertID()`

https://golang.org/pkg/database/sql/#Result
