### ISSUE TITLE
compilation failed for go1.6rc2

### ISSUE THREAD

**Issue by Son-Lam** [jmoiron/sqlx#203]
Hi,

I tried to run "go get github.com/jmoiron/sqlx"
**# runtime
/usr/local/go/src/runtime/os2_linux_generic.go:12: _SS_DISABLE redeclared in this block
	previous declaration at /usr/local/go/src/runtime/os2_linux.go:8
/usr/local/go/src/runtime/os2_linux_generic.go:13: _NSIG redeclared in this block
	previous declaration at /usr/local/go/src/runtime/os2_linux.go:9
/usr/local/go/src/runtime/os2_linux_generic.go:14: _SI_USER redeclared in this block
	previous declaration at /usr/local/go/src/runtime/os2_linux.go:10
/usr/local/go/src/runtime/os2_linux_generic.go:15: _SIG_BLOCK redeclared in this block
	previous declaration at /usr/local/go/src/runtime/os2_linux.go:11
/usr/local/go/src/runtime/os2_linux_generic.go:16: _SIG_UNBLOCK redeclared in this block
	previous declaration at /usr/local/go/src/runtime/os2_linux.go:12
/usr/local/go/src/runtime/os2_linux_generic.go:17: _SIG_SETMASK redeclared in this block
	previous declaration at /usr/local/go/src/runtime/os2_linux.go:13
/usr/local/go/src/runtime/os2_linux_generic.go:18: _RLIMIT_AS redeclared in this block
	previous declaration at /usr/local/go/src/runtime/os2_linux.go:14
/usr/local/go/src/runtime/os2_linux_generic.go:24: sigset redeclared in this block
	previous declaration at /usr/local/go/src/runtime/os2_linux.go:20
/usr/local/go/src/runtime/os2_linux_generic.go:26: rlimit redeclared in this block
	previous declaration at /usr/local/go/src/runtime/os2_linux.go:22
/usr/local/go/src/runtime/panic1.go:11: paniclk redeclared in this block
	previous declaration at /usr/local/go/src/runtime/panic.go:535
/usr/local/go/src/runtime/panic1.go:11: too many errors
**

Could you take a look.

Best Regards,

**Comment by jmoiron** [comment]
I don't think this is an sqlx issue:

```go
17:15:39 jmoiron@sanji:$GOPATH/src/github.com/jmoiron/sqlx (master)$ go version
go version go1.6rc2 linux/amd64
17:15:44 jmoiron@sanji:$GOPATH/src/github.com/jmoiron/sqlx (master)$ go test
PASS
ok  	github.com/jmoiron/sqlx	3.673s
```

**Comment by RaviTezu** [comment]
Hoping this may help others,
I had the same issue, when I upgraded Go from 1.5 to 1.6. 
To fix it, I had to remove all the extracted files and extract the 1.6 tar again. If you are still seeing the issue, you may try restarting your Terminal as well.

**Comment by P1xt** [comment]
Thanks for that @RaviTezu - removing /usr/local/go and extracting the files again fixed the problem for me as well. I'm wondering if there were some leftover 1.5 files from my prior install that didn't play well with 1.6.

**Comment by jmoiron** [comment]
Thanks @RaviTezu!

**Comment by ryalman** [comment]
Thanks @RaviTezu

**Comment by mackjoner** [comment]
Thanks @RaviTezu

**Comment by kafeltz** [comment]
Thanks @RaviTezu

**Comment by nickma** [comment]
Worked here as well.

**Comment by Ripounet** [comment]
"removing /usr/local/go and extracting the files again" yes exactly! Thanks a lot.

**Comment by kunth** [comment]
As we are told to use the command (from [go doc](https://golang.org/doc/install) )
`tar -C /usr/local -xzf go$VERSION.$OS-$ARCH.tar.gz`

So from go verion 1.5 -> 1.6 , I had the "_SS_DISABLE redeclared" error.
At the same time, back from 1.6 -> 1.5, I had the "import cycle not allowed" error

So the easy way is to remove the original folder(e.g. /usr/local/go), then exec the `tar -C /usr/local -xzf go$VERSION.$OS-$ARCH.tar.gz` command, and it turns out OK.

**Comment by zuoRambo** [comment]
so, this isn't a `go version` problem

Because we fix the `lfstackPack redeclared in this block previous declaration` error by degrade the version from **1.6.4** to **1.6.2**.

**Comment by cainiaofei** [comment]
fix this question through remove and tar again. But why this work? what happend?
