### ISSUE TITLE
Using PostgreSQL Default Value

### ISSUE THREAD

**Issue by AdrianLungu** [jmoiron/sqlx#207]
Hello,

I'm not sure if I missed something or not but is it possible to use Postgres' Default Values for NamedExecs (for example) ? 

I have a case where I'm doing an upsert, but I want the default value (serial) to be used in case my Id column is null or 0. Is there any way to currently do this ?

Thanks!

**Comment by jmoiron** [comment]
How would you achieve this without using NamedExecs?  I'm afraid I need a little more context, like maybe some sample SQL or some way you were doing this before NamedExecs, so I can see how they might (or might not) complicate the issue.

**Comment by AdrianLungu** [comment]
Sure, it's not a specific NamedExec issue per-se, just wanted to know if this could be added. I could fork the project and try to implement this myself.

For example
```
INSERT INTO dataset (id, age, name, description)
VALUES (DEFAULT, 42, 'fred', 'desc');

INSERT INTO dataset (age, name, description)
VALUES (42, 'fred', 'desc');
```

This is how one has to do an INSERT for PostgreSQL to use the Default Value of the Id column, which in this case is a serial (default value should auto-increment id). 

Using NamedExec I'm trying to do the following:
```
INSERT INTO admins (id, username, password)
VALUES (:id, :username, :password)
ON CONFLICT (id) DO UPDATE
SET username = EXCLUDED.username
password = EXCLUDED.password
```
Now, the problem is, I can't have Id null (using sql.NullInt64), and if I leave it as int, the value is 0, and PostgreSQL will just add the 0 id column. 

I was thinking if it would be possible use the "DEFAULT" value for Id if Id = 0.

Hope that makes more sense.

**Comment by jmoiron** [comment]
Once it becomes a query parameter, I'm not sure you can pass `DEFAULT`;  if you tried to do it as a string, it'd become the equivalent of `'DEFAULT'` instead.  You might have to check this before you query  and run one query in one case or another in another.

**Comment by jmoiron** [comment]
I think this problem is probably out of scope for sqlx.
