### ISSUE TITLE
JSONText MarshalJSON() pointer receiver prevents embedding

### ISSUE THREAD

**Issue by bfallik** [jmoiron/sqlx#217]
Currently this method is defined as
```
func (j *JSONText) MarshalJSON() ([]byte, error)
```
with a pointer receiver. This prevents JSONText from being embedded into a larger, Marshal()-able struct like so:
```
type MyThing struct {
  MyField int
  MySubField JSONText 
}
```
Calls to json.Marshal(MyThing) will fail since MySubField won't have a pointer receiver in this context. Instead `encoding/json` will interpret the field as a `[]byte` and marshal it into a base64 string, e.g.:
```
{
  "MyField": 0,
  "MySubField": "bnVsbA==" 
}
```

One simple solution might be to drop the pointer from the method:
```
--- a/go/src/_vendor/github.com/jmoiron/sqlx/types/types.go
+++ b/go/src/_vendor/github.com/jmoiron/sqlx/types/types.go
@@ -56,7 +56,7 @@ func (g *GzippedText) Scan(src interface{}) error {
 type JSONText json.RawMessage

 // MarshalJSON returns the *j as the JSON encoding of j.
-func (j *JSONText) MarshalJSON() ([]byte, error) {
+func (j JSONText) MarshalJSON() ([]byte, error) {
        return j, nil
 }
```

**Comment by jmoiron** [comment]
The pointer could be embedded.  I'm not sure why this is a big problem, maybe I need to see a use case where a pointer doesn't work.

**Comment by bfallik** [comment]
@jmoiron thanks for the response. What use case do you need beyond the sample code I pasted above? That code snippet is representative of an actual problem we're trying to solve at work. We're trying to embed a JSONText struct inside another struct.

Without this change json.Marshal() ignores MarshalJSON() and instead chooses to decode the field as base64 []byte.

**Comment by jmoiron** [comment]
I think using the pointer would work fine but since it doesn't need a pointer receiver and it doesn't really break anything to make this change I've modified it.
