### ISSUE TITLE
another db table name format

### ISSUE THREAD

**Issue by codinl** [jmoiron/sqlx#219]
Now the table column name is the lowercase of the struct attribute.  In my project, the exists table column name is like this:  "UserName" -> "user_name"。 How can i make this？ thanks。

**Comment by elithrar** [comment]
Use struct tags:

```go
type Person struct {
    UserName string `db:"user_name"`
}
```

There are examples in the docs (http://jmoiron.github.io/sqlx/). Hope that's clear.

**Comment by codinl** [comment]
thanks reply。

I use gorm before,  gorm has a function 'gorm.SingularTable(true)',   I think this is better. 

`
	orm, err = gorm.Open()
	if err != nil {
		panic(err)
	}

	orm.SingularTable(true)
` 
 
I suggest sqlx add something like this.  thanks。

**Comment by jmoiron** [comment]
Hi @codinl.  I think that [name mapping](http://jmoiron.github.io/sqlx/#mapping) does what you want.
