### ISSUE TITLE
Why did I get wrong syntax?

### ISSUE THREAD

**Issue by RuniVN** [jmoiron/sqlx#221]
This code does not work at all. 
```
const driverName = "mysql"
var (
    schema = `
    CREATE TABLE transactions (
    id varchar(255) NOT NULL,
    source_account_id varchar(255) DEFAULT NULL,
    target_account_id varchar(255) DEFAULT NULL,
    source_wallet_id varchar(255) DEFAULT NULL,
    target_wallet_id varchar(255) DEFAULT NULL,
    amount bigint(20) unsigned DEFAULT NULL,
    text varchar(255) DEFAULT NULL,
    created_at timestamp NULL DEFAULT NULL,
    PRIMARY KEY (id)
    );
    CREATE TABLE wallets (
    id varchar(255) NOT NULL,
    account_id varchar(255) DEFAULT NULL,
    currency_id varchar(255) DEFAULT NULL,
    balance bigint(20) DEFAULT NULL,
    type int(10) unsigned DEFAULT NULL,
    target bigint(20) DEFAULT NULL,
    created_at timestamp NULL DEFAULT NULL,
    closed_at timestamp NULL DEFAULT NULL,
    PRIMARY KEY (id)
    );`
    db *sqlx.DB
)
// MySQLDB stands for sqlx.DB for further testing
type MySQLDB sqlx.DB
// Init connects to the MySQL server, initializes DB schema and
// returns the DB instance.
func Init(dsn string) (db *sqlx.DB, err error) {
    // Open the database connection
    db, err = sqlx.Connect(driverName, dsn)
    if err != nil {
        return
    }
    db.MustExec(schema)
    return
}
```
I got an error:

```panic: Error 1064: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'CREATE TABLE wallets (
	id varchar(255) NOT NULL,
	account_id varchar(255) DEFAU' at line 11 [recovered]
	panic: Error 1064: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'CREATE TABLE wallets (
	id varchar(255) NOT NULL,
	account_id varchar(255) DEFAU' at line 11```

But when I separate it into 2 schema, it works:

```
const driverName = "mysql"
var (
    schema1 = `
    CREATE TABLE transactions (
    id varchar(255) NOT NULL,
    source_account_id varchar(255) DEFAULT NULL,
    target_account_id varchar(255) DEFAULT NULL,
    source_wallet_id varchar(255) DEFAULT NULL,
    target_wallet_id varchar(255) DEFAULT NULL,
    amount bigint(20) unsigned DEFAULT NULL,
    text varchar(255) DEFAULT NULL,
    created_at timestamp NULL DEFAULT NULL,
    PRIMARY KEY (id)
    );`
    schema2 = `CREATE TABLE wallets (
    id varchar(255) NOT NULL,
    account_id varchar(255) DEFAULT NULL,
    currency_id varchar(255) DEFAULT NULL,
    balance bigint(20) DEFAULT NULL,
    type int(10) unsigned DEFAULT NULL,
    target bigint(20) DEFAULT NULL,
    created_at timestamp NULL DEFAULT NULL,
    closed_at timestamp NULL DEFAULT NULL,
    PRIMARY KEY (id)
    );`
    db *sqlx.DB
)
// MySQLDB stands for sqlx.DB for further testing
type MySQLDB sqlx.DB
// Init connects to the MySQL server, initializes DB schema and
// returns the DB instance.
func Init(dsn string) (db *sqlx.DB, err error) {
    // Open the database connection
    db, err = sqlx.Connect(driverName, dsn)
    if err != nil {
        return
    }
    db.MustExec(schema1)
    db.MustExec(schema2)
    return
}
````
Please check this.

**Comment by jmoiron** [comment]
PostgreSQL via libpq style drivers (eg `github.com/lib/pq`) are the only ones that I know of that will execute multiple statements with one call.  These are driver limitations/decisions, rather than issues in sqlx or `database/sql`.  I suggest splitting up your statements and executing them one at a time;  you can still put them in a `[]string` to execute them easily in a loop, eg.
