### ISSUE TITLE
sqlx.NewDb vs sqlx.NewDB

### ISSUE THREAD

**Issue by lancecarlson** [jmoiron/sqlx#224]
Which is the right API now? Code says NewDb but the docs say NewDB.

**Comment by elithrar** [comment]
`NewDb` is correct - it's always been like that: https://github.com/jmoiron/sqlx/blame/master/sqlx.go#L240

**Comment by lancecarlson** [comment]
This needs to be updated then:

http://jmoiron.github.io/sqlx/

Under Connection to Your Database

**Comment by jmoiron** [comment]
Yuck it should probably be NewDB though.  Can't change it now.  I could add an alias but it'd just clutter up the API docs.

**Comment by jmoiron** [comment]
Fixed in the docs.  Thanks for the report!
