### ISSUE TITLE
Need I to close the connection or statements?

### ISSUE THREAD

**Issue by mageddo** [jmoiron/sqlx#233]
On [sql](https://golang.org/pkg/database/sql/) I need to close ResultSet,Rows,DB, etc. on *sqlx* need I close Get, MustExec, Select, and the Transactions?

**Comment by vahe** [comment]
Get and Select will automatically close the rows. MustExec returns connection before returning, so again no need to close anything. Working with transactions requires calling either Commit or Rollback to return the connection to the pool.

Take a look at http://jmoiron.github.io/sqlx/ for more info.

**Comment by mageddo** [comment]
@vahe It sounds strange because I am running [this example](https://github.com/mageddo/go-examples/tree/1.0.9/gowiki-vestigo-3rd-sql-dao/webapp) that I've written then I got `to many clients` error

```go
func GetConnection() (*sqlx.DB) {
	db, err := sqlx.Open("postgres", "postgres://root:root@postgresql-server.dev/wiki?sslmode=disable")
	db.SetMaxIdleConns(2)
	db.SetMaxOpenConns(95)
	if err != nil{
		log.Println("m=GetConnection,msg=connection has failed", err)
	}
	return db
}

// here the problem occur
db := crud.GetConnection()
err = db.Get(u, `SELECT description FROM wiki WHERE name=$1`, title)
if err != nil {
	log.Println("m=LoadPage,msg=error at select query: ", err)
	return u, err
}
```

```bash
$ siege -c400 -t10s http://localhost:8989/edit/elvis-23
2016/06/16 13:50:13 m=LoadPage,msg=error at select query:  pq: sorry, too many clients already
2016/06/16 13:50:13 M=wiki-edit, msg=loaded
```

**Comment by vahe** [comment]
You should have only one instance of `db`, since `db` itself is not a connection.
See "Connecting to your database" section: http://jmoiron.github.io/sqlx/#connecting

**Comment by mageddo** [comment]
Oh, makes sense now, I will test it, thanks a lot @vahe

**Comment by mageddo** [comment]
[updated example](https://github.com/mageddo/go-examples/blob/1.1.0/gowiki-vestigo-3rd-sql-dao/webapp/crud/sql.go)
It works, now my app have only one `sqlx.DB` instance

```go
var (
	pool *sqlx.DB
	err error
	)
func init(){
	pool, err = sqlx.Open("postgres", "postgres://root:root@postgresql-server.dev/wiki?sslmode=disable")
	pool.SetMaxIdleConns(5)
	pool.SetConnMaxLifetime(2 * time.Minute)
	pool.SetMaxOpenConns(95)
	if err != nil{
		log.Println("m=GetPool,msg=connection has failed", err)
	}
}

/**
  abre a conexão com o banco de dados
 */
func GetConnection() (*sqlx.DB) {
	return pool
}
```

**Comment by coolaj86** [comment]
Does `db.SetMaxOpenConns(100)` apply across _all_ instances or just the one named?

Do I need to do something to close  Will the db just get garbage collected when it drops out of scope?

I have to connect to an arbitrary number of user-defined databases (**not the same database**) for multiple users as part of a data load process. These `db` instances are **not long-lived**. Basically there's just one SELECT statement to import some data and then it closes. So there may be 20 different databases at 20 different IP addresses.open for a single query (and then never used again) at any given time.
