### ISSUE TITLE
Panic without error message

### ISSUE THREAD

**Issue by xEtarusx** [jmoiron/sqlx#235]
I get a panic without any error message and the program get stuck in there when trying to connect to a mysql database on a port where no database is listening

Used connection string: user:password@tcp(database.host.com:44444)/Database?allowOldPasswords=true&parseTime=true

In this example I used port 44444 but it works with any port which is not the database port (default 3306).

Program get stuck showing this:
`$ ./Program.exe`
`panic:`

Nothing more happens after this.

It's really annoying because the first time I got into this by a typo in the port I searched for hours and couldn't find the mistake because there is no error message at all.

**Comment by jmoiron** [comment]
This sounds pretty unusual but as far as I can tell it's very unlikely to be an sqlx problem.

* what is the precise code that brings about this panic?  what OS version and Go version?
* does this happen when you attempt to conenct with these parameters using `database/sql.Open` directly?

**Comment by xEtarusx** [comment]
The function i'm calling in the looks like this:

    func (db *database) connectToDatabase() *sqlx.DB {
	      connectionString := db.Username + ":" + db.Password + "@tcp(" + db.Server + ":" + strconv.Itoa(db.Port) + ")/" + db.Database + "?allowOldPasswords=true&parseTime=true"

	      // Open the mysql connection
	      connection, err := sqlx.Connect("mysql", connectionString)
	      if err != nil {
		     panic(err)
	      }

	      return connection
}


I tried it with sql.Open now and this won't even say panic to me.
If I execute it it doesn't throw an error... but the following querys throw an error because there is no valid connection. Weird...

**Comment by jmoiron** [comment]
`sqlx.Connect` automatically attempts a `db.Ping`, and if this fails, it returns an error from that.  This is why `sql.Open` might work, as `sql.Open` merely _initialises a connection pool_ but does not create a connection until one is asked for.  Since you are connecting with the wrong arguments and panicking on an error I think this is expected behavior, although it's odd you do not get any data from the panic.
