### ISSUE TITLE
Get last inserted rows

### ISSUE THREAD

**Issue by hangll** [jmoiron/sqlx#236]
This might be a dump question. Suppose I inserted a new row into a table with `db.NamedExec`, what is the recommended way to get the inserted row? (Especially I need the ID). 

Currently, I'm doing something like 
```
res, _ := DB.NamedExec(s, obj)
id, _ := res.LastInsertId()
```

However, I don't think this approach supports concurrent request.

**Comment by jmoiron** [comment]
@hangll it depends on your database.  Some databases do not support `LastInsertId` but have other methods of retrieving this information, eg in PostgreSQL you can do `INSERT ... RETURNING ...` and then do `db.Query` or `db.Get`
