### ISSUE TITLE
LastInsertedId should be LastInsertedID?

### ISSUE THREAD

**Issue by Narven** [jmoiron/sqlx#242]
Hi,

I've been using sqlx for a while, and recently I've notice about LastInsertedId, shouldn't it be LastInsertedID... following the Go standards?

[https://github.com/golang/go/wiki/CodeReviewComments#initialisms](https://github.com/golang/go/wiki/CodeReviewComments#initialisms)

Thanks

**Comment by seanhagen** [comment]
Ran into this when my linter discovered this -- I think it's LastInsertId because that's how it is in in the [database/sql.Result interface](https://golang.org/pkg/database/sql/#Result).

So this is really an issue with the database/sql library, not this one.

**Comment by Narven** [comment]
thats a nice point... seems that I need to go a bit higher. thanks

**Comment by sh0umik** [comment]
but i am getting error sayin `no LastInsertId available`

**Comment by Narven** [comment]
@sh0umik can we see the code where you are running the query and where ur trying to get the `LastInsertId` ?

**Comment by Narven** [comment]
besides is `LastInsertedId` not `LastInsertId`

**Comment by RayfenWindspear** [comment]
Does anyone know what the naming convention is for this in Go? My code is littered with XyzId instead of XyzID.

**Comment by Narven** [comment]
It shoud be XyzID

Check this link: [https://github.com/golang/go/wiki/CodeReviewComments#initialisms](https://github.com/golang/go/wiki/CodeReviewComments#initialisms)

**Comment by sh0umik** [comment]
the problem with LastInsertedId is that postgresql driver doesnot implemented this interface but should be fine with other sql..  And its LastInsertId(int64, error)

**Comment by RayfenWindspear** [comment]
@Narven You have just made my day with that link.

**Comment by Narven** [comment]
> one is glad to be of service

**Comment by jmoiron** [comment]
Yes, Indeed [result.LastInsertId](https://golang.org/pkg/database/sql/#Result) is the reason why this goes against normal conventions on initialisms.  I think it might even be special-cased by the linter.
