### ISSUE TITLE
no LastInsertId available in Postgresql

### ISSUE THREAD

**Issue by sh0umik** [jmoiron/sqlx#245]
```
result, err := d.db.Exec(
		`INSERT INTO profile (user_id, updated_at)
		VALUES ($1, $2)
		ON CONFLICT(user_id) DO UPDATE
		SET updated_at=$2 where profile.user_id=$1 RETURNING user_id;`,
		p.UserId, p.UpdatedAt,
	)
	id, err := result.LastInsertId()
	fmt.Printf(" id : %d", id)
```
The query works fine and returned user_id on psql shell but i am not getting any id . It panics saying `no LastInsertId available`

**Comment by mewben** [comment]
You can use `d.db.Get(&lastInsertID, query, args)`

**Comment by jmoiron** [comment]
Yes, this is a limitation in the Postgres driver (and perhaps some assumptions made during the development of database/sql) and not a bug `database/sql` or `sqlx`.
