### ISSUE TITLE
NamedQueryRow missing?

### ISSUE THREAD

**Issue by krhubert** [jmoiron/sqlx#250]
I found [issue](https://github.com/jmoiron/sqlx/issues/102) mentions the same thing and I want to talk about it again.

It was 2 years ago, and the NamedExec and NamedQuery are still in the API, so maybe time to think about include NamedQueryRow. It would be a lot cleaner not to check error twice as it is in proposal solution:

```Go
row, err := NamedQueryRow(...)
if err != nil {
  return err
}
if err := row.Scan(...); err != nil {
  return err
}
```

compare to other function that returns only *sqlx.Row

```Go
row := NamedQueryRow(...)
if err := row.Scan(...); err != nil {
  return err
}
```

**Comment by jmoiron** [comment]
The rest of the Named* stuff is missing in preference to using `PrepareNamed` and then using the `NamedStmt`;  the API gets really big if that is all duplicated everywhere and I don't know that there's any gain from it.

**Comment by timbunce** [comment]
Since this topic crops up from time to time (I've just had the same question) a note in the docs would be helpful to others stumbling down the same path.

**Comment by sidh** [comment]
Just stumbled upon this issue. The problem with PrepareNamed is that sometimes you cannot use prepared statements - for example when you use PGBouncer with transaction pooling and do not want to use transactions (https://wiki.postgresql.org/wiki/PgBouncer#Feature_matrix_for_pooling_modes).
