### ISSUE TITLE
bind date string error:“not unexpected `:` while reading named param at xx”

### ISSUE THREAD

**Issue by linlexing** [jmoiron/sqlx#252]
```go
package main
import (
	"log"
	"github.com/jmoiron/sqlx"
)
func main() {
	if _, _, err := sqlx.Named("select '2016-01-01 12:01:01' as a from dual", nil); err != nil {
		log.Panic(err)
	}
}
```
output:
>panic: unexpected `:` while reading named param at 24

The reason for the error is not neglected colon within single quotes

**Comment by linlexing** [comment]
can use double colon  escape the string:
>select '2016-01-01 12::01::01' as a from dual

This is good!

**Comment by urbanovich** [comment]
you can do else like this:

`m := &model.StampedRequest{}
	e := &enitity.StampedRequest{}

	m.Id = id
	m.IsDeleted = true
	m.UpdatedAt = time.Now().UTC()

	q := fmt.Sprintf(`UPDATE %s SET is_deleted=:is_deleted, updated_at=:updated_at WHERE id=:id RETURNING *`, m.GetTableName())

	log.Println(q)
	if rows, err := repo.pool.NamedQueryContext(*repo.ctx, q, m); err != nil {
		log.Println(err)
		return nil, err
	}`
