### ISSUE TITLE
Occasionally retrieving "connection timed out" errors

### ISSUE THREAD

**Issue by seanlindo** [jmoiron/sqlx#257]
I get this error every so often when utilizing sqlx with pgx, and I believe it's a configuration error on my end:

`error: 'write tcp [redacted-ip]:[redacted-port]->[redacted-ip]:[redacted-port]: write: connection timed out`

This occurs when attempting to read from the database. I init sqlx in the startup phase:

    package main

    import (
	    _ "github.com/jackc/pgx/stdlib"
	    "github.com/jmoiron/sqlx"
    )

    //NewDB attempts to connect to the DB
    func NewDB(connectionString string) (*sqlx.DB, error) {
	    db, err := sqlx.Connect("pgx", connectionString)

	    if err != nil {
		    return nil, err
	    }

	    return db, nil
    }

Any structs responsible for interacting with the database have access to this pointer. The majority of them utilize `Select` or `Get`, and I understand those return connections to the pool on their own. There are two functions that use `Exec`, and they only return the result and error at the end of the function. 

## Other Notes
* My Postgres db supports 100 `max_connections`
* I only showed a few active connections at the time of this error
* I am not using `SetMaxIdleConnections` or `SetMaxOpenConnections`
* Refreshing the page and triggering the request again always works

Any tips on what might be happening here?

EDIT: I did not mention this server is on compose.io, which in turn is hosted on AWS. Is it possible AWS turns these connections into zombies because they've been open for so long and the timeout occurs after unsuccessfully trying them one by one?

**Comment by KingRider** [comment]
This seems to work

```
conn := "user@ip/password"
dbConn, err = sqlx.Open("pgx", conn)
if err != nil && dbConn == nil {
	log.Fatal(err)
	time.Sleep(time.Second * 10)
	return nil
}
defer dbConn.Close()
```

Timeout is can try **for / break / continue** with sleep 10 seconds to reconnect

**Comment by seanlindo** [comment]
@KingRider I've actually never had a problem in this init code. The database is always available and ready for connections-- the issue seems to stem from the network being unhappy with long-running connections and killing them off (the client never knows when this happens). I was able to find a workaround by setting the maximum lifetime of the connection, but I have more follow-up to do on my end to see if I can shorten the TCP Keep Alives.

I will render any further discussion [here](https://github.com/jackc/pgx/issues/205#event-843840740)
