### ISSUE TITLE
JSONText broken

### ISSUE THREAD

**Issue by gravis** [jmoiron/sqlx#266]
Until recently, `JSONText` was acting like a string, and since 6708aed04f34b30c834ad320fd3c2b8c61dd4c76, we have a lot of issues with this type.
See the following code:

```go
package main

import (
        "encoding/json"
        "fmt"
        "github.com/jmoiron/sqlx/types"
)

type X struct {
        Z types.JSONText
}

func main() {
        x := X{
                Z: types.JSONText("[]"),
        }
        bytes, _ := json.Marshal(x)
        fmt.Printf("%s\n", string(bytes))
}
```

before the commit, it was returning `{"Z":[]}` as expected, and after `{"Z":"W10="}`

**Comment by gravis** [comment]
The problem is located here: https://github.com/jmoiron/sqlx/commit/6708aed04f34b30c834ad320fd3c2b8c61dd4c76#diff-9457129899e29a9925770fb1644a14f3R63

**Comment by gravis** [comment]
Ok, got it.

```go
// MarshalJSON returns the *j as the JSON encoding of j.
func (j *JSONText) MarshalJSON() ([]byte, error) {
	if len(*j) == 0 {
		*j = _EMPTY_JSON
	}
	return *j, nil
}
```

should be 

```go
// MarshalJSON returns the j as the JSON encoding of j.
func (j JSONText) MarshalJSON() ([]byte, error) {
	if len(j) == 0 {
		j = _EMPTY_JSON
	}
	return j, nil
}
```

Otherwise the func is never called.

**Comment by gravis** [comment]
@jmoiron 6708aed is really is breaking change for us, can you take a look at this?
Thanks

**Comment by jmoiron** [comment]
I don't see a reason to have that mutation in the first place.   f9b4c7a passed tests, can you make sure it works for you?

**Comment by gravis** [comment]
It works!
Thanks a lot :)
