### ISSUE TITLE
Context support 

### ISSUE THREAD

**Issue by c4milo** [jmoiron/sqlx#278]
Go 1.8 introduced context.Context support in the SQL package. I would love to see sqlx catching up with it.

**Comment by luna-duclos** [comment]
sqlx.Tx seems to be missing QueryxContext.

**Comment by dixonwille** [comment]
As I mentioned in #312 this PR/Issue broke it for Go 1.8? Seems to be missing a few functions or something on the structure.

**Comment by jmoiron** [comment]
The above ended up being an issue with GOROOT.   Also I think the remaining issues were resolved earlier this year so I'm closing this ticket!
