### ISSUE TITLE
Getting "missing destination name" error even when field exists  in the target structure

### ISSUE THREAD

**Issue by yibin001** [jmoiron/sqlx#298]
hi,my struct is ：

`
type Transaction struct {
    Id            int64
    newCateId int64
}
`

my sql schema

> CREATE TABLE mytable(Id INTEGER PRIMARY KEY AUTOINCREMENT, newCateId INTEGER);

When I'm trying to load this structure from DB

`
err = DB.Get(t, "SELECT * FROM mytable WHERE Id=$1", id)
`

I always get an error: "missing destination name newCateId"

if i modify column name "newCateId" to "cateId",it works。

is column name can't startwith "new"?

thanks

**Comment by jhngrant** [comment]
@yibin001 Try this:

type Transaction struct {
	ID int64 `db:"Id"`
	NewCateId int64 `db:"newCateId"`
}

**Comment by yibin001** [comment]
@jhngrant 
oh,yes,it works,thank you.
