### ISSUE TITLE
how to assign a  field to be an existing pointer instance

### ISSUE THREAD

**Issue by carbin-gun** [jmoiron/sqlx#309]
Hi @jmoiron : 

if I have a Object which may have only a few instances .I will keep the instances in memory, but write to table with only a symbol. so the Table Object in Golang would have a field which is a pointer field ,so how can I assign to that field after the database query.

Example Case :

```go
type Company struct {
    ID int64 
    Name string
    ...
    PayMethod *PayMethod
}

type PayMethod struct {
    Code int
    Name string
    Symbol string
    URL string
}

var(
    Paypal = &PayMethod{...}
    AliPay = &PayMethod{...}
    WeChatPay = &PayMethod{...}
)

func (p *PayMethod) Value() (driver.Value, error){
    return p.Code
}
// How should I write Scan or any other way?

```
If  I want to query from DB to fetch a proper PayMethod to assign to the Company struct built. what should I do.  I want to use the **Type way, but then the receiver can be only *Type in Golang. What should I do to finish this.

**Comment by jmoiron** [comment]
You will have to implement `Scanner` as well.  Check out an [old but relevant blogpost](http://jmoiron.net/blog/built-in-interfaces) on implementing custom types for scanning.

**Comment by carbin-gun** [comment]
@jmoiron ,The Scanner implementation can't work at this situation. Because the Scan method can only be bind to the receiver of `*PayMehod` like the example.But the existed instance in this situation can't be granted to the receiver. 
```go
func (p *PayMethod) Scan(src interface{}) error {
   *p = xxx // You can't assign value to p here ,like p = xxx,right?
}
```
