### ISSUE TITLE
select no work if any record has any field null.

### ISSUE THREAD

**Issue by thanhngvpt** [jmoiron/sqlx#311]
Hi All.
I have code 
```
products := []Product{}
db.Select(&products, "SELECT * FROM product")
```

but in product if has any record has any field null select won't work and my `products` will become `empty slice`.

What wrong with me?
Many thanks.

**Comment by jmoiron** [comment]
You aren't checking the error output of `Select`;  you probably have a field in your `Product` struct that cannot be null (eg an Int or a String), see `sql.NullInt64`, `sql.NullString`, etc.
