### ISSUE TITLE
pq: SSL is not enabled on the server with sslmode=disable

### ISSUE THREAD

**Issue by xenu256** [jmoiron/sqlx#316]
```text
"pq: SSL is not enabled on the server" error with "sslmode=disable"
```

Windows 8.1, Postgres 9.6

**Comment by xenu256** [comment]
OK, found what's wrong, not sqlx related.

**Comment by pmyjavec** [comment]
@xenu256 what was it related too?

**Comment by stevenspiel** [comment]
@xenu256 yeah, I'm also having that issue

**Comment by hero0926** [comment]
@xenu256 also having same problem...how did you solve it

**Comment by alella** [comment]
It defaults to ssl, don't mention the `sslmode`
```go
sqlx.Connect("postgres", "user=foo dbname=bar")
```
