### ISSUE TITLE
godoc needs examples of placeholder usage

### ISSUE THREAD

**Issue by therealplato** [jmoiron/sqlx#318]
Hi I'm new to this project, I tried:
```
	row, err := db.conn.Queryx("select * from emails where request_uuid=?", "uuid1")
```

and I get `syntax error at or near \"?\"`

Is this package responsible for substituting values into placeholder parameters?

Can you show how to placeholder on https://godoc.org/github.com/jmoiron/sqlx#DB.Queryx ?

**Comment by jmoiron** [comment]
I think you are probably using a db with different [bindvars](http://jmoiron.github.io/sqlx/#bindvars).  Try:

```go
query := db.conn.Rebind("select * from emails where request_uuid=?")
row, err := db.conn.Queryx(query, "uuid1")
```

FWIW, sqlx does _not_ substitute values into placeholders, that's actually generally done by the rdbms on the other side of the connection.

**Comment by therealplato** [comment]
cheers @jmoiron!
