### ISSUE TITLE
Proposal: Use "IN (?)" and $1, $2, .. together

### ISSUE THREAD

**Issue by felixguertler** [jmoiron/sqlx#338]
Sqlx is awesome! However, I haven't found a clean way to combine an efficient way to combine an `IN (?)` statement with specific parameters.

This is can happen quite a bit in queries like this for example:
`SELECT * FROM t1 WHERE user IN (?) AND some_date > $1`

To achieve this I've added the following to `Rebind`:
```
...
// find existing bindings
re := regexp.MustCompile("\\$(\\d+)")
mm := re.FindAllStringSubmatch(query, -1)
maxe := 0

for _, m := range mm {
  im, _ := strconv.Atoi(m[1])
  if im > maxe {
    maxe = im
  }
}

qb := []byte(query)
// Add space enough for 10 params before we have to allocate
rqb := make([]byte, 0, len(qb)+10)
j := 1 + maxe
...
```

I know it's not up to the code standard of the rest of the library so I'm not submitting a PR but maybe something like this could be added to `Rebind` or to a new func with this purpose?

**Comment by hellowords** [comment]
use `sqlx.Named()`
[docs](https://jmoiron.github.io/sqlx/#namedParams)
