### ISSUE TITLE
It doesn't work for lastest golang version

### ISSUE THREAD

**Issue by zhonglushu** [jmoiron/sqlx#349]
I just get some meaningless Numbers.

**Comment by jhngrant** [comment]
@zhonglushu are you able to say what database and driver are you using?

**Comment by zhonglushu** [comment]
Mysql，table schema like this:
<img width="427" alt="unknow2" src="https://user-images.githubusercontent.com/11389621/29852613-acdb4bde-8d6d-11e7-9b1f-5b109efdc509.png">

**Comment by zhonglushu** [comment]
The driver is https://github.com/go-sql-driver/mysql

**Comment by jhngrant** [comment]
@zhonglushu to try and replicate this issue, are you also able to share a snippet of Go code? - both the code you are code using to call sqlx and the struct.

In case you haven't already tried, try a forced rebuilding of packages in your project using:

```
go build -a
```

**Comment by zhonglushu** [comment]
The sqlx code is:
`if r.Method == "GET" {
		db, err := sqlx.Connect("mysql", "root:*******@tcp(localhost:3306)/test?charset=utf8")
		if err != nil {
			panic(err.Error())
		}

		rows, err := db.Queryx("SELECT * FROM population")
		if err != nil {
			panic(err.Error())
		}
		m := map[string]interface{}{}
		for rows.Next() {
			err = rows.MapScan(m)
			if err != nil {
				panic(err.Error())
			}
			fmt.Println(m)
			fmt.Println("-------------")
		}
}`

the running result is:
<img width="1029" alt="unknow3" src="https://user-images.githubusercontent.com/11389621/29860377-8788e9f6-8d98-11e7-8d45-1bc95631301d.png">

**Comment by zhonglushu** [comment]
I found scan method can not convert columns read from the database into *interface{}

**Comment by jhngrant** [comment]
@zhonglushu I'm not seeing the same issue. Out of interesting, what does the output look like when you range over the map instead? :

```
	rows, err := db.Queryx("SELECT * FROM population")
	if err != nil {
		panic(err.Error())
	}
	m := map[string]interface{}{}
	for rows.Next() {
		err = rows.MapScan(m)
		if err != nil {
			panic(err.Error())
		}
		// fmt.Println(m)
		for i := range m {
			fmt.Printf("%v\n", m[i])
		}
                fmt.Println("-------------")
	}
```

**Comment by zhonglushu** [comment]
It doesn't work，I found scan method can not convert columns read from the database into *interface{}.
For example, the code below can work, but the result is unexpectedly:
`var name interface{}
			var code int
			var year int
			var total float64
			err = rows.Scan(&name, &code, &year, &total)
			if err != nil {
				fmt.Println("Get values from database error")
				fmt.Println(err.Error())
			}

			popuMap := make(map[string]interface{})
			popuMap["Region_name"] = name
			popuMap["Region_code"] = code
			popuMap["Year"] = year
			popuMap["Total_population"] = total`

After I modify the code "var name interface{}" like this:
`var name string
			var code int
			var year int
			var total float64
			err = rows.Scan(&name, &code, &year, &total)
			if err != nil {
				fmt.Println("Get values from database error")
				fmt.Println(err.Error())
			}

			popuMap := make(map[string]interface{})
			popuMap["Region_name"] = name
			popuMap["Region_code"] = code
			popuMap["Year"] = year
			popuMap["Total_population"] = total`
I found the code runs properly, why?

**Comment by jhngrant** [comment]
@zhonglushu This behavior seems to be specific to the 'github.com/go-sql-driver/mysql' driver.
See: https://github.com/go-sql-driver/mysql/issues/366
and https://github.com/go-sql-driver/mysql/issues/407

**Comment by zhonglushu** [comment]
@jhngrant Thank you very much!
