### ISSUE TITLE
sqlx.Connect("postgres", addr) freezes

### ISSUE THREAD

**Issue by mraxus** [jmoiron/sqlx#353]
I'm building a docker image with a simple sqlx connection and running it in docker-compose.
For some reason, the statement see snippet below does not connect or error out, it just freezes.
No idea why. It is related to using `alpine:latest` docker base image. I have not tracked down the issue completely but connecting to the image from the *psql* cli works like a charm (with the same connection string as used for in the statement (`addr`).

The code I've used in my setup:

```go
package main

import (
	"fmt"
	"github.com/jmoiron/sqlx"
	_ "github.com/lib/pq"
	"os"
)

func main() {
	addr := os.Getenv("DB")
	fmt.Println("Postgres addr: " + addr)

	_, err := sqlx.Connect("postgres", addr)

	if err != nil {
		fmt.Println("Could not connect...")
	} else {
		fmt.Println("Connecting successful")
	}
}
```

As stated above, this code causes problem when building a go executable that is run within a container based on the image `alpine:latest`, together with *docker-compose`.

I have set up a test project to reproduce the problems I am facing with:
https://github.com/mraxus/mystery-golang-alpine

Would love to get some help into this and hope this is an actual bug in your lib (otherwise I am wasting your time, which is not my intention)

Cheers, Marcus

**Comment by jhngrant** [comment]
@mraxus The connection string of the pq driver includes a ```connect_timeout``` parameter. If it is not specified it means the ```Connect``` method will wait indefinitely. Have you tried setting this parameter? Any error returned because of a timeout may provide a clue:

```
      _, err := sqlx.Connect("postgres", addr)
```

See: https://godoc.org/github.com/lib/pq#hdr-Connection_String_Parameters

**Comment by mraxus** [comment]
Thanks, I will look into that @jhngrant!

I have also discovered that sqlx is not the issue to this. It's something more basic. I made a test excluding sqlx where I use only `lib/pq`. I get the same results: https://github.com/mraxus/mystery-golang-alpine/pull/2

So I will close the issue for now but will comment here if I find out anything more.

**Comment by mraxus** [comment]
So I got this when setting the timeout (after adding a `panic(err)` in the error path):

```
alpine_1    | Could not connect...
alpine_1    | panic: dial tcp 205.251.219.44:5432: i/o timeout
alpine_1    |
alpine_1    | goroutine 1 [running]:
alpine_1    | main.main()
alpine_1    | 	/go/src/project.com/me/main.go:18 +0x219
o2_alpine_1 exited with code 2
```

**Comment by jhngrant** [comment]
@mraxus Looks like you might need to open port TCP 5432 in your Docker file.

**Comment by mraxus** [comment]
@jhngrant 

In the `docker-compose.yml` it is open:

```
postgres:
    image: postgres:latest
    ports:
        - "5432"
...
```

**Comment by mraxus** [comment]
Or you mean the `Dockerfile`?

When going into (`docker exec -it e321a743fdde /bin/sh`) to the `alpine` (as named in the yml file) docker container and installing the *postgresql* package and connecting the the same connection string as used in `sqlx.Connect()`, I connect without issues.

**Comment by jhngrant** [comment]
@mraxus I guessing the port needs to be mapped:
```
ports:
      - 5432:5432
```

**Comment by jhngrant** [comment]
@mraxus Have a look at: https://docs.docker.com/engine/examples/postgresql_service/

**Comment by mraxus** [comment]
Hmm, I think that it's the DNS lookup that is weird somehow. Thanks to your timeout I noticed that the IP used from within the golang program is different from what I get when pinging from within the container:

`dial tcp 205.251.219.236:5432: i/o timeout`

vs

```
/ # ping postgres
PING postgres (172.17.0.2): 56 data bytes
```

**Comment by mraxus** [comment]
So I assume this is the reason. Thanks @jhngrant for helping me tracking this issue down.
Must be a DNS lookup issue within the container.

**Comment by mraxus** [comment]
After some more digging with a colleague, we have found a solution to my problem (with running connecting between *docker-compose* containers by using the `GODEBUG=netdns=cgo` environment variable. That forces go to use the default resolver, and not Go's own.  So just adding 
that in the `docker-compose.yml` solved my problem.

See more about name resolution: https://golang.org/pkg/net/#hdr-Name_Resolution

**Comment by mraxus** [comment]
@jhngrant The real problem turned out to be a *search domain* set up on our corporate network. This is by default propagated to each container in their `/etc/resolv.conf` and for some reason that entry affected to `alpine` containers, but not the `golang`. By overwriting the config in `docker-compose.yml`, the issue has been completely resolved. Such a crazy hunt, elusive prey...

The docker issue referenced above is not the cause for this.

**Comment by jhngrant** [comment]
@mraxus Thanks for coming back to explain how you resolved the issue. Useful to note.

My experience with containers is limited. The smart people are telling me FaaS (Lambda, Google/Azure Functions) is the future and to give containers a miss. I get the costs benefits, infinite scalability, lots of metrics, etc. But I'm certain serverless will simply swap one set of pain points with another. And then there's vendor lock-in...

In the meantime, I'll stick with familiar VMs. Besides I don't want to lose any more hair.
