### ISSUE TITLE
Consider using semver for golang/dep support

### ISSUE THREAD

**Issue by blockloop** [jmoiron/sqlx#361]
golang/dep is [on a path](https://github.com/golang/dep/wiki/Roadmap) to become the official golang dependency tool. One way to make your repository work with release versions is to use semver as specified [in the dep README](https://github.com/golang/dep#semantic-versioning). 

Would you consider using semver tags to tag your releases?

**Comment by jhngrant** [comment]
@blockloop fyi https://github.com/jmoiron/sqlx/issues/360#issuecomment-341804760

> As for an official version, I am waiting for more of a consensus for versioning in Go; probably when dep reaches blessed status and has a clear position on it.

**Comment by sagikazarmark** [comment]
Regardless of how dep advances in the Go ecosystem, I think it's already quite clear that there is (some could say desperate) need for proper library versioning. Other package management solutions already exist ad widely used by the community which kinda requires proper versioning as well.

But even if we put package management aside, vendoring unversioned dependencies is simply a nigthmare IMO.

So I think this decision should not depend on the future of dep, but that's my 2 cents only.

**Comment by flibustenet** [comment]
Maybe it's time to tag with a valid semver.
https://research.swtch.com/vgo

**Comment by the-destro** [comment]
Bumping this, as versioning is coming in 1.11

**Comment by flibustenet** [comment]
Just added a PR to add `go.mod` and `go.sum` before next release #446

**Comment by glaslos** [comment]
Closed with [1.2.0](https://github.com/jmoiron/sqlx/releases/tag/v1.2.0 ) release
