### ISSUE TITLE
Hook system

### ISSUE THREAD

**Issue by asdine** [jmoiron/sqlx#364]
I would like to monitor and log some queries on application side but in order to do that i have to wrap the entire API and call my before and after functions for every method.
Is having a hook system something that you might be interested with ?

**Comment by glaslos** [comment]
Doesn't transactions and context solved that for you?

**Comment by asdine** [comment]
It was more to have a generic way to automate metrics reporting when running queries.
We managed to do it by calling top level functions like `sqlx.Get` etc and passing our own implementations of `Execer`, `Queryer` etc.
Sqlx has now enough primitives to do the job
