### ISSUE TITLE
how to select more than one level non-embedded struct ?

### ISSUE THREAD

**Issue by zhangfh517** [jmoiron/sqlx#371]
```
type A struct{
    foo string
}

type B struct {
   a A
}
type C struct {
  b B
}
```
I want to select C struct in db, and then get foo . 
Can this be achieved using sqlx? 
My english is pool ,  I hope you can understand.

**Comment by jhngrant** [comment]
@zhangfh517 Use embedded structs. See:

http://jmoiron.github.io/sqlx/#advancedScanning

https://github.com/jmoiron/sqlx/blob/master/sqlx_test.go#L381

**Comment by zhangfh517** [comment]
@jhngrant  thanks for replying
I use a anonymous struct to contains all the struct.  I can get the nested struct now.
