### ISSUE TITLE
NamedExec query does not work with sql server.

### ISSUE THREAD

**Issue by vishal8492** [jmoiron/sqlx#374]
README example with NamedExec query does not work with sql-server.

I'm using mssqldb driver.  (github.com/denisenkom/go-mssqldb)

MustExec returns following error :
Err :  result :  <nil> mssql: Incorrect syntax near '?'.

**Comment by vishal8492** [comment]
This is because of while compiling query all args are appended with '?' , we should just use @P{increment} there? 

@jmoiron What do you think should I add bindtype for sqlserver? 

Also, maybe MustExec may convert $1, $2 to @p1,@p2 based on bindtype ?

**Comment by Zenlil** [comment]
This is rather urgent as the denisenkom/go-mssqldb-driver seems to deprecate the "mssql"-driver and encourage the "sqldriver" with named parameters.

I absolutely love the Select and Get with built-in mapping/scanning and would love to get that with named params.
