### ISSUE TITLE
Empty result

### ISSUE THREAD

**Issue by freezlite** [jmoiron/sqlx#375]
How to check if Get function return err with empty result ?

**Comment by jhngrant** [comment]
@freezlite ```Get``` can return an ```sql.ErrNoRows``` error if there are no rows in the result set - note some database drivers may return a driver specific error instead:

```
i := Category{}

err := db.Get(&i, `
SELECT
  id
  , category
FROM categories
WHERE id = 'non-existent';
`)

if err == sql.ErrNoRows {
	log.Println("Not Found")
} else if err != nil {
	log.Fatalln(err)
}
```

**Comment by k0fi** [comment]
This does not work for me. When the result is empty `Not Found` does not work.  `go version 1.10`
