### ISSUE TITLE
MySQL BIT(x) INSERT INTO fails 

### ISSUE THREAD

**Issue by mrx23dot** [jmoiron/sqlx#403]
MySQL expect the following bit expression for updating a BIT(1) field:
   INSERT INTO unit (valid) VALUES (b'0');

but sqlx inserts it with quotes: "b'0'", which is rejected by MSQL.
      tx.MustExec("INSERT INTO unit (valid) VALUES (?);", "b'0'")  <-- fails

works with vulnerable string formating: 
   stm := fmt.Sprintf("INSERT INTO unit (valid) VALUES (%s);", "b'0'")  --> passes, no quotes

**Comment by jmoiron** [comment]
Late to this, apologies.  Representation for bindvars is going to be based on the driver.  However, I wouldn't expect any driver to understand that `"b'0'"` is the bit 0;  bindvars are not formatted into strings, but rather sent up to the server as is, with the arguments all formatted according to the server's protocol, and then dealt with safely by the server.  This is why they are safe against injection attacks.

This issue (and others like it) is something to look into with the upstream driver.
