### ISSUE TITLE
Field names with underscore can read but not insert/update using named vars in MySql

### ISSUE THREAD

**Issue by sathishvj** [jmoiron/sqlx#418]
I'm seeing a weird issue with write/insert/update in MySql.  If a field has an underscore in it, it reads fine but named write does not insert the actual value.  Instead it puts the "zero" value.

With: 
```
type T struct {
    DeviceId string `db:"device_d"`
    Abcd string `db:"abcd"`
}
```

So, below code works.
`insert into t1 (device_id, abcd) values (?, ?) 
`
But below code does not work only for deviced_id.  But it works for abcd.  
`insert into t1 (device_id, abcd) values (:device_id,  :abcd) 
`
Read also works fine.  So it is not an issue with capitalization of the field.   

Am I doing something else wrong?

**Comment by TeemoWan** [comment]
insert into t1 (device_id, abcd) values (:device_id, :abcd)

**Comment by sathishvj** [comment]
@TeemoWan that's how it is in my code.  I'll fix my typo in the issue.

**Comment by sathishvj** [comment]
Not an issue.  Just idiocy on my part.  I was reusing the same struct for `db` and `json` and forgot to put in the json tag.
