### ISSUE TITLE
Suggest use v1.x.x as tag name, or dep will use sqlx-v1.0 as the first choice

### ISSUE THREAD

**Issue by adanteng** [jmoiron/sqlx#451]
I use dep tool, dep will get sqlx-v1.0 which has a problem, Rows.Close() will cause panic because mutex disabled by copy, take a long time to find this problem.

Please use tag name like v1.x.x.

**Comment by glaslos** [comment]
Closed with [1.2.0](https://github.com/jmoiron/sqlx/releases/tag/v1.2.0 ) release
