### ISSUE TITLE
NamedQuery doesn't correctly parse queries involving sql variables

### ISSUE THREAD

**Issue by ikilledthecat** [jmoiron/sqlx#455]
compileNamedQuery function does not correctly compile queries which involve sql variables. e.g
```sql
SELECT @name := "name", :age, :first, :last;
SELECT @name := "name", ?, ?, ?;
SELECT @name := "name", $1, $2, $3;
SELECT @name := "name", :age, :first, :last;
```
This affects the NamedQuery & NamedQueryExec functionality provided by the library as far as I can tell.

**Comment by jmoiron** [comment]
thank you for the patch :bowing_man:
