### ISSUE TITLE
Issue using Named parameters with SQL Server

### ISSUE THREAD

**Issue by sunit-joshi** [jmoiron/sqlx#457]
I've a sql string like:

`INSERT INTO ADAccount (samaccount, userprincipal, employeetype, extattr9, extattr10, manager, pwdlastsetutc, pwdexpiresutc) VALUES (@samaccount, @userprincipal, @employeetype, @extattr9, @extattr10, @manager,@pwdlastsetutc, @pwdexpiresutc)`

When I try this (acNew is a Struct), I get an error:
ntstm, err := Db.PrepareNamedContext(ctx, sqlString)
_, err = ntstm.Exec(acNew) 

mssql: Must declare the scalar variable "@samaccount".

Any thoughts?
SJ

**Comment by jmoiron** [comment]
Should be fixed with https://github.com/jmoiron/sqlx/pull/406
