### ISSUE TITLE
Add support for cznic/ql in Rebind()

### ISSUE THREAD

**Issue by LinuxMatt** [jmoiron/sqlx#464]
Would you agree to add support for  'cznic/ql' (pure go) database in the Rebind() function (bind.go) ?
The prepared statement syntax for parameters is "$1 , $2 ..."
Regards,

**Comment by jmoiron** [comment]
Sure, if you open a pull request for that diff I'll merge it.  If not, I'll add it shortly.

**Comment by LinuxMatt** [comment]
#466

**Comment by jmoiron** [comment]
Thanks!
