### ISSUE TITLE
db.NamedExec did not work as expected

### ISSUE THREAD

**Issue by ORESoftware** [jmoiron/sqlx#465]
I have this golang code:

```golang

        s1 := Person{ID: 1, Firstname: "Alex", Lastname: "Chaz", Email: "alex@example.com"}
	people = append(people, s1)
	s2 := Person{ID: 2, Firstname: "Jason", Lastname: "Statham", Email: "jason@example.com"}
	people = append(people, s2)

	db := dbs.GetDatabaseConnection()
	db.Exec(schema)

	tx := db.MustBegin()

	tx.MustExec("INSERT INTO person (firstname, lastname, email) VALUES ($1, $2, $3)", s1.Firstname, s1.Lastname, s1.Email)
	tx.MustExec("INSERT INTO person (firstname, lastname, email) VALUES ($1, $2, $3)", s2.Firstname, s2.Lastname, s2.Email)

	// Named queries can use structs, so if you have an existing struct (i.e. person := &Person{}) that you have populated, you can pass it in as &person

	// tx.NamedExec("INSERT INTO person (firstname, lastname, email) VALUES (:Firstname, :Lastname, :Email)", s1)
	// tx.NamedExec("INSERT INTO person (firstname, lastname, email) VALUES (:Firstname, :Lastname, :Email)", s2)
	tx.Commit()
```

the tx.MustExec queries worked fined, but the tx.NamedExec queries did not, is there anything obvious that I did wrong? weird. (Note that the two queries that I commented out are the ones that weren't working.)

**Comment by yzzyx** [comment]
Isn't the issue that the default mapper for named queries is `strings.ToLower`.

If you try your queries with:
``
tx.NamedExec("INSERT INTO person (firstname, lastname, email) VALUES (:firstname, :lastname, :email)", s1) 
``
instead, does it work?

**Comment by ORESoftware** [comment]
my struct has uppercase first chars for all fields, but i will try that tomorrow thx

**Comment by yzzyx** [comment]
your struct needs tho have uppercase first chars, so that the fields are exported. just update the query.

**Comment by ORESoftware** [comment]
yeah that was my question, how should update the query?  this query didn't work, but probably should have:

```js
 tx.NamedExec("INSERT INTO person (firstname, lastname, email) VALUES (:Firstname, :Lastname, :Email)", s1)
```

**Comment by yzzyx** [comment]
the most probable reason your query does not work is that you've typed `:Firstname, :Lastname, :Email`, etc. with uppercase first chars, but you should type them with all lowercase, as so: `:firstname, :lastname, :email`.

**Comment by jmoiron** [comment]
As @yzzyx has stated, sqlx uses a mapper to fit local Go names to database names.  It uses this mapper to fit the Go struct attributes to named vars in your query as well, so:

```go
type Person struct {
    EmailAddress string
}
```

Person.EmailAddress would map to `emailaddress` (with the default mapper).  You will need to make your queries compatible with the mapper you want;  if you want to use the same names in Go and in the database (and all of your database names would be exported Go names) then you can use a Noop mapper:

```
func NoopMapper(s string) string {
    return s
}

db.MapperFunc(NoopMapper)
```

**Comment by agnivade** [comment]
Is it possible to have a rebind functionality for namedexec queries too? The problem is that my code needs to work with MySQL and Postgres both. So queries with positional arguments work when I rebind it, but namedExec queries don't. Since they contain struct field names.

The `MapperFunc` conditionally handles the struct fields. But that isn't useful unless I can rebind the params in Named queries as well.
