### ISSUE TITLE
sqlx.DB should be interface

### ISSUE THREAD

**Issue by Allenyn** [jmoiron/sqlx#499]
sqlx.DB should be interface !

**Comment by ScreamingTaco** [comment]
I don’t think that’s a good idea. In the standard library’s implementation of sql.DB, it is not an interface it is it’s own struct. From what I can see, sqlx.DB is a struct that has a pointer to an sql.DB and a pointer to a mapper. What is your reasoning behind saying it should be an interface?

**Comment by jmoiron** [comment]
I don't think packages should expose interfaces.  Users should define their own interfaces that are limited to the API they require and then exchange implementations as needed.
