### ISSUE TITLE
[Question] Is possible to specify a schema when we are building the connection string?

### ISSUE THREAD

**Issue by marticrespi** [jmoiron/sqlx#509]
Hi, I have an example working on postgres in the public schema.

````
	return fmt.Sprintf("host=%s port=%s user=%s password=%s dbname=%s %v",
		viper.GetString("db.host"), viper.GetString("db.port"), viper.GetString("db.user"), viper.GetString("db.pass"), viper.GetString("db.name"), ssl)
````
Is any option to specify which schema we want in that configuration? I have tried using in the query  like schema.table but it throws an error:

````
Severity:"ERROR"
Code:"42P01"
Message:"relation "billing.contract" does not exist"
````
I have been searching in the documentation but I can't find any about it.

Thanks!

**Comment by speza** [comment]
Can you use `search_path=schema` in your `fmt.Sprintf`?
