### ISSUE TITLE
Logging interface

### ISSUE THREAD

**Issue by cmelbye** [jmoiron/sqlx#52]
Do you think it could be useful to use `log.Logger` and allow the ability to set a custom logger instead of using `log.Println`? Execv and friends are nice, but it would be great if those logs could be sent somewhere other than STDOUT.

**Comment by gravis** [comment]
I really like the way [logrus](https://github.com/Sirupsen/logrus) is handling this.
Hooks can be registered, and will receive a copy of the log entry. Maybe `Exec`, `Select`, etc. could act the same. Adding logging / performance measurement would be easily achived, without creating a new type and wrap all the methods (which I has to do). Wrapping is weak and doesn't support API changes very well :(

**Comment by gravis** [comment]
(weak -> New methods are not wrapped until we write the code)
(changes -> Need to update all wrappers where API changed)

**Comment by vergenzt** [comment]
Just thought I'd chime in with interesting idea I saw suggested on StackOverflow: https://stackoverflow.com/a/33042034/718180

> sqlx has a very interesting abstraction in the form of the following interfaces:
>  - [`sqlx.Execer`](https://godoc.org/github.com/jmoiron/sqlx#Execer)
>  - [`sqlx.Queryer`](https://godoc.org/github.com/jmoiron/sqlx#Queryer)
> 
> They are used all through the library as the interfaces representing the functionality of using strings as SQL queries.
> 
> ...
> 
> So if you are willing not to use the DB type directly but instead use the underlying free functions of the library, you can use the following structure to wrap your db into objects that perform logging:
> 
> ```go
> type QueryLogger struct {
>     queryer sqlx.Queryer
>     logger  *log.Logger
> }
> 
> func (p *QueryLogger) Query(query string, args ...interface{}) (*sql.Rows, error) {
>     p.logger.Print(query, args...)
>     return p.queryer.Query(query, args...)
> }
> 
> func (p *QueryLogger) Queryx(query string, args ...interface{}) (*Rows, error) {
>     p.logger.Print(query, args...)
>     return p.queryer.Queryx(query, args...)
> }
> 
> func (p *QueryLogger) QueryRowx(query string, args ...interface{}) *Row {
>     p.logger.Print(query, args...)
>     return p.queryer.QueryRowx(query, args...)
> }
> ```
> 
> And when connecting to your database:
> 
> ```go
> db, err := sqlx.Connect("postgres", "user=foo dbname=bar sslmode=disable")
> if err != nil {
>     log.Fatalln(err)
> }
> 
> ql := &QueryLogger{db, yourLogger}
> 
> sqlx.Select(ql, &people, "SELECT * FROM person ORDER BY first_name ASC")
> ```

**Comment by macrael** [comment]
How does one 'trivially implement this in any codebase'? Where is the hook to get at logging every query?

**Comment by ptman** [comment]
https://github.com/simukti/sqldb-logger
