### ISSUE TITLE
Custom bind types for custom database drivers

### ISSUE THREAD

**Issue by mr337** [jmoiron/sqlx#559]
We are using sqlx through pop for our ORM. We needed to modify the pq driver to include a custom authentication with a small tweak and register as a new driver. We found that since the driver is registered and has a different name than `postgres` we are binded as `UNKOWN` causing issues for prepared queries.

There are a few issues such as https://github.com/jmoiron/sqlx/issues/400 and https://github.com/jmoiron/sqlx/pull/401 to register new binds. These look to be on hold by https://github.com/jmoiron/sqlx/issues/390#issuecomment-369124648.

Would anyone be interested in a PR to add options that are prefixed `customX` binding? Similar to https://github.com/jmoiron/sqlx/pull/391/files#diff-fbe43523c613db26c24df36d429e7ad3R24 following the pattern of `custompostgres`, `custommysql`, `customoracle`. This would allow a method for devs to use a custom driver without modifying sqlx directly.  The only downside is a custom driver would need to be registered as `customX`. 

Thoughts? Happy to put in a PR!

**Comment by andy-kimball** [comment]
I'd also like to see this solved, as I've just implemented the open source [copyist](https://github.com/cockroachdb/copyist) SQL mocking library, and then ran into this issue when trying to use `sqlx` with it. I've put comments over in the #560 PR with another possible approach that would allow for a bit more naming flexibility than this proposal, but even this proposal is better than nothing at all.

**Comment by jmoiron** [comment]
This fixed by `sqlx.BindDriver` merge from November.  It will be in 1.3.x
