### ISSUE TITLE
Could not find name `col_name` in interface

### ISSUE THREAD

**Issue by sourcec0de** [jmoiron/sqlx#56]
For anyone getting the error message in the title.

Try changing the struct key names before continuing your search. It may help you save a lot of time.
##### Good - struct

``` go
type Item struct {
    Id      string `db:"_id"`
    Name    string `db:"item_name"`
    BrandId string `db:"brand_id"`
}
```
##### BAD!! - struct

``` go
type Item struct {
    _id       string
    item_name string
    brand_id  string
}
```

**Comment by palfrey** [comment]
For those of you further puzzled at this: Capitalisation of your struct key names, or it can't find things. Because Go.
