### ISSUE TITLE
Question: can I insert a structure as a row

### ISSUE THREAD

**Issue by shaunc** [jmoiron/sqlx#570]
I would like to do approximately the opposite of struct scan (ie equiv to json.Marshal): insert a structure into columns:
```
insert into foo values ( $1 )
```
Where `$1` should be expanded to the columns of a structure. If I try
```
stmt = tx.Preparex(`insert into foo values ( $1 )`)
stmt.Exec(fooRow)
```
where foo row is a structure (tagged with `db:"..."` specifying column mapping), it doesn't work. Are there any workarounds? Do I have to read the tags and build the db query myself, and use reflect to get the params from the structure? :(

**Comment by Jammizzle** [comment]
`NamedExec` is used for inserting structures as rows, is it not? This is opposed to using Exec that is positional

**Comment by Jammizzle** [comment]
A quick demo
```golang

type Event struct {
	ID                         int       `json:"event_id,omitempty" db:"pEventID"`
	Name                       string    `json:"name" db:"sName" validate:"empty=false"`
	Description                string    `json:"description" db:"sDescription" validate:"empty=false"`
	CreateDate                 time.Time `json:"date_created" db:"dCreated" validate:"empty=false"`
	StartDate                  time.Time `json:"start_time" db:"dStart" validate:"empty=false"`
	EndDate                    time.Time `json:"end_time" db:"dEnd" validate:"empty=false"`
}
tx, _ := db.d.Beginx()
if _, err := tx.NamedExec(sqlCreateEvent, event); err != nil {
	tx.Rollback()
	return err
}
```

**Comment by shaunc** [comment]
Ah -- cool! :) I overlooked that (perhaps there could be a doc improvement to highlight?).

Thanks!
