### ISSUE TITLE
How can I handle nullable datetime2 columns? — mssql

### ISSUE THREAD

**Issue by Maxiride** [jmoiron/sqlx#572]
## Database
SQL Server (mssql driver)

## Column type
`datetime2`

## Scenario

Mapping a struct to a database table which has a column of type `datetime2` which is a nullable column.

I know I can use `time.Time` to map a table to a struct and viceversa but is there a proper way to map it in the case that I am retrieving a null time?
`database/sql` doesn't have `sql.NullTime`.

**Comment by KlimSidorov** [comment]
Why can't you have a pointer to time.Time in your struct?
In this case you will have nil after scanning.

type Obj struct {
  time *time.Time
}

**Comment by Maxiride** [comment]
I ended up using the package gopkg.in/guregu/null.v3/zero and its brother gopkg.in/guregu/null.v3/null which offers types to convert null values to their respective null or zero forms of the destination type.
