### ISSUE TITLE
panic when using prepare statement

### ISSUE THREAD

**Issue by wilsoon16** [jmoiron/sqlx#586]
` http: panic serving 10.255.13.175:52450: runtime error: invalid memory address or nil pointer dereference
goroutine 106 [running]:
net/http.(*conn).serve.func1(0xc00021ed20)
        /usr/local/go/src/net/http/server.go:1767 +0x139
panic(0x83a400, 0xc217d0)
        /usr/local/go/src/runtime/panic.go:679 +0x1b2
github.com/tokopedia/risk-automation/test_dashboard/api.Handler.InsertTestSuite(0xc000091110, 0x959fa0, 0xc0002288c0, 0xc000224c00)
        /home/nakama/go/src/github.com/tokopedia/risk-automation/test_dashboard/api/api.go:81 +0x4d5
net/http.HandlerFunc.ServeHTTP(0xc000021260, 0x959fa0, 0xc0002288c0, 0xc000224c00)
        /usr/local/go/src/net/http/server.go:2007 +0x44
github.com/gorilla/mux.(*Router).ServeHTTP(0xc0000ee000, 0x959fa0, 0xc0002288c0, 0xc000224a00)
        /home/nakama/ht3/hammertime/src/github.com/gorilla/mux/mux.go:210 +0xe2
net/http.serverHandler.ServeHTTP(0xc00012a1c0, 0x959fa0, 0xc0002288c0, 0xc000224a00)
        /usr/local/go/src/net/http/server.go:2802 +0xa4
net/http.(*conn).serve(0xc00021ed20, 0x95aca0, 0xc000200cc0)
        /usr/local/go/src/net/http/server.go:1890 +0x875
created by net/http.(*Server).Serve
        /usr/local/go/src/net/http/server.go:2928 +0x384`

Hi i encounter this issue  when using prepare  statement like below:
`sqldb := h.DB

		tx, _ := sqldb.Beginx()
		stmt, err := tx.Prepare("INSERT INTO te_risk_test_execution (test_suite_name, service, status, create_time, xray_key, environment) VALUES($1,$2, '0', now(), 'simulation aja', $3) returning execution_id")
		if err != nil {
			fmt.Println(err)
			errMessage := ErrorMessage{Message: "internal server error"}
			json.NewEncoder(w).Encode(errMessage)
			return
		}

		defer stmt.Close()

		var testinsert = TestSuiteStatus{Service: params["service"], Environment: testSuite.Environment}
		err = stmt.QueryRow(testSuite.TestSuite, testSuite.Service, testSuite.Environment).Scan(&testinsert.ID)
		if err != nil {
			log.Fatal(err)
		}

		tx.Commit()

		json.NewEncoder(w).Encode(testinsert)`

any idea why this  happen ?

**Comment by Vorlif** [comment]
The function `Beginx()` also returns an error and you should also check it.
