### ISSUE TITLE
"sql: error no rows" while trying to find a row by NULL column

### ISSUE THREAD

**Issue by KlimSidorov** [jmoiron/sqlx#593]
The problem is that sqlx doesn't convert nil to "IS NULL". See examples below.

Here is an example that **does not work** properly:
```
q := `
  SELECT "id", "title", "text", "next_id", "book_id"
  FROM "pages"
  WHERE "book_id"=$1, "next_id"=$2
  LIMIT 1
`
row := tx.QueryRowx(q, id, nil)
```

Here is an example that **works**:
```
q := `
  SELECT "id", "title", "text", "next_id", "book_id"
  FROM "pages"
  WHERE "book_id"=$1, "next_id" IS NULL
  LIMIT 1
`
row := tx.QueryRowx(q, id)
```

I didn't find this behavior in docs, so decided to post it here.
May be it will be better to add "sqlx.Nil" and "sqlx.NotNil" vars or something like this?

**Comment by jmoiron** [comment]
This is an interesting idea but I don't think there's a way to support this;  sqlx would have to rewrite the query in a way that I don't think would be anticipated by most users.
