### ISSUE TITLE
it is time to release a new version

### ISSUE THREAD

**Issue by 652028815** [jmoiron/sqlx#625]
1.2.0 is too old

**Comment by sk0g** [comment]
I don't think "too old" is helpful feedback. Unless you have specific feedback/ issues, what do you want them to do, just package up the same release under a new version to make it look newer?

**Comment by jmoiron** [comment]
I'm going through the backlog.  I'll cut a release after I'm done.

**Comment by kravemir** [comment]
I had to use the latest unreleased version, because `sqlx.In` is panicking on some input values in version 1.2.0.

In mean time, until @jmoiron makes a new release, if you are running into issues, you use:

```bash
go get github.com/jmoiron/sqlx@0794cb1f47ee444eda9624f952ab8a370bec22de # commit ID of current master
```

**Comment by dcormier** [comment]
Any updates on this?

**Comment by richardliao** [comment]
I'm using @kravemir's solution. Anticipating new release too.

**Comment by jmoiron** [comment]
1.3.0
