### ISSUE TITLE
ERROR: bind message has 2 result formats but query has 1 columns when using sqlx.Connect

### ISSUE THREAD

**Issue by goku321** [jmoiron/sqlx#633]
I am getting `ERROR: bind message has 2 result formats but query has 1 columns (SQLSTATE 08P01)` when I do `sqlx.Connect("pgx", connString)`.

My DSN looks like this: `host=hostname user=user database=db password=password port=6432 sslmode=require`

**Comment by jmoiron** [comment]
Does this happen if you use `database/sql` directly, eg. `sql.Open("pgx", connString)`

**Comment by goku321** [comment]
No, I tried it with `database/sql` and it worked fine.

**Comment by jmoiron** [comment]
This worked for me:

```go
package sqlx

import (
	"os"
	"testing"

	_ "github.com/jackc/pgx/v4/stdlib"
)

func TestPgxConn(t *testing.T) {
	dsn := os.Getenv("SQLX_POSTGRES_DSN")
	db, err := Connect("pgx", dsn)
	if err != nil {
		t.Fatal(err)
	}
	if db == nil {
		t.Fatal("db was nil")
	}
}
```

Going to need more information to reproduce:  pgx version, sqlx version, go version, postgresql version, and a failing test case.

**Comment by goku321** [comment]
I'm confused. It worked for me as well for a few times after I created this issue. But most of the time, it's failing. I think it has something to do with test cases running concurrently. I have two packages and both of them have integration tests(both creates a connection to the db). The error is gone when I set the `-p` flag to 1 while running the tests.

But, I still don't understand what the error means?

**Comment by goku321** [comment]
I think I'm doing something wrong. I got this as well `bind message supplies 2 parameters, but prepared statement \"\" requires 3`

All my db methods are like this:
```
func (pg *pgdb) GetUser(ctx context.Context, tenantID int, userID string) ([]User, error) {
	sqlString := `
		SELECT
		column1,
		column2
		FROM users
		WHERE tenant_id=$1 AND user_id=$2 LIMIT 1
	`
	var user User
	err := pg.conn.QueryRowxContext(ctx, sqlString, tenantID, userID).StructScan(&user)
	if err != nil {
		if err == sql.ErrNoRows {
			return []User{}, nil
		}

		return []User{}, err
	}

	return []User{user}, nil
}
```

**Comment by jmoiron** [comment]
Assuming that `pg.conn` is an `*sqlx.DB`, this should work, and parallelism should not be a problem.  The error you're getting back is saying that you do not have enough parameters for the bindvars you've provided, but in this case you've used `$1` and `$2` and supplied 2.

Are you sure the error message is coming from this test and not from another one?  I'm afraid without a runnable test, I'm still not sure what is going wrong.

**Comment by goku321** [comment]
Here's the code that's failing:
```
package db

import (
	"os"
	"testing"

	_ "github.com/jackc/pgx/stdlib"
	"github.com/jmoiron/sqlx"
	"github.com/stretchr/testify/require"
)

var (
	postgresTestDB PG
)

func setup() {
	connString := os.Getenv("PG_TEST_DATABASE")
	conn, err := sqlx.Connect("pgx", connString)
	if err != nil {
		panic(err)
	}

	// Note: safe to suppress error here as it has been take care of above.
	db, _ := NewPG(conn)

	postgresTestDB = db
}

func TestMain(m *testing.M) {
	setup()
	ok := m.Run()
	postgresTestDB.Close()
	os.Exit(ok)
}
```
![image](https://user-images.githubusercontent.com/12848015/84734066-9adbd780-afbd-11ea-9282-3b34e556b20f.png)

In the above screenshot, line no. 20 is where I'm am doing `sqlx.Connect`

**Comment by goku321** [comment]
I get the same error even with `database/sql`. Here's the complete error:
`pgx.PgError(pgx.PgError{Severity:"ERROR", Code:"08P01", Message:"bind message has 2 result formats but query has 1 columns", Detail:"", Hint:"", Position:0, InternalPosition:0, InternalQuery:"", Where:"", SchemaName:"", TableName:"", ColumnName:"", DataTypeName:"", ConstraintName:"", File:"pquery.c", Line:643, Routine:"PortalSetResultFormat"})`

Surprisingly, it works completely fine sometimes.

**Comment by goku321** [comment]
My mistake, I was using the older version of `pgx`. Changed my import from `github.com/jackc/pgx/stdlib` to `github.com/jackc/pgx/v4/stdlib` and it worked fine.
