### ISSUE TITLE
how to query one column list?

### ISSUE THREAD

**Issue by Jeeesie** [jmoiron/sqlx#634]
I want to query user_id from user table which has two columns "user_id", "role_id",
mysql query is :
select role_id from role_user where user_id in ('4861fe8581347a259e4faa13a8ef550e','6613831cac9e4597abbd0138116a8f3c')

how do I use sqlx?
```
`async fn find_role_ids_by_user_ids(&self, user_ids: Vec<String>) -> anyhow::Result<Vec<String>> {
        let mut role_ids: Vec<String> = Vec::new();
        let mut ids_str = "".to_string();
        for user_id in user_ids{
            if !ids_str.is_empty(){
                ids_str.push(",".parse()?);
            }
            ids_str.push_str(format!("\'{}\'", user_id).as_ref());
        }
        let query = format!("select role_id from role_user where user_id in ({})", &ids_str);
```

        // println!("select role_id from role_user where user_id in ({})", &ids_str);
        let mut q = sqlx::query_as::<_, String>(&query);
        match q.fetch_all(&self.pool).await {
            Ok(stream) => {
                Ok(role_ids)
            },
            Err(e) => Err(anyhow!("{:?}", e)),
        }
}`

this cause an Error:
the trait bound `for<'c> std::string::String: sqlx_core::row::FromRow<'c, sqlx_core::mysql::row::MySqlRow<'c>>` is not satisfied

**Comment by leopku** [comment]
@Jeeesie You are using Rust version sqlx. But this lib was just for golang :laugh:.

**Comment by jmoiron** [comment]
Sorry, try https://github.com/launchbadge/sqlx
