### ISSUE TITLE
Request to add latest tag for master branch

### ISSUE THREAD

**Issue by feverxai** [jmoiron/sqlx#638]
I am using godror driver and install sqlx by using `go get github.com/jmoiron/sqlx` as readme said but unfortunately it installed sqlx@1.2.0 which is not has godror driver name in BindType function so I have to reinstall by using `go get github.com/jmoiron/sqlx@master`

**Comment by nvx** [comment]
Looks like the v1.2.0 tag is 2018 vintage. Might be worth adding a v1.3.0 tag pointing to the current master version if master is considered stable at the moment. @jmoiron

**Comment by jmoiron** [comment]
Added.
