### ISSUE TITLE
`LastInsertId()` WRONG for sqlite3 with ROWID

### ISSUE THREAD

**Issue by AlbinoGeek** [jmoiron/sqlx#645]
Exactly as the topic says.

I have an empty database, then I insert one record.

I call `LastInsertId` on the result of the insert, and get `1` as the result.

The real ID is `0` -- not `1`. This is entirely wrong.

## Versions

|Thing|Version|
|-|-|
|Golang|1.14.6 linux/amd64|
|Kernel|5.7.14-200.fc32.x86_64|
|OS|Fedora 32 (Workstation Edition)|
|sqlx|master commit 0794cb1|
|sqlite3|v1.14.2 commit [862b959](https://github.com/mattn/go-sqlite3/commit/862b95943f99f3b40e317a79d41c27ac4b742011)|

**Comment by arp242** [comment]
sqlx simply calls the `LastInsertId` provided by the driver; so this is a bug in sqlite, if it's a bug at all (it probably isn't).

I don't know why you're expecting an ID of 0?

**Comment by AlbinoGeek** [comment]
As watching the database using an `sqlite3` cli, I could see the inserted record received an ID of `0`. I have since dropped this package from my project due to this issue.

**Comment by jmoiron** [comment]
fwiw I cannot reproduce this;  I've updated the version of sqlite3 that is shipped with sqlx recently to 1.14.6, maybe that's changed something.

**Comment by AlbinoGeek** [comment]
Specifically, the table you are inserting into must be using sqlite3's equiv of AUTOINCREMENT, called `ROWID` to trigger this issue.
