### ISSUE TITLE
Cross-compiling or statically linking `sqlx` fails because of OpenSSL

### ISSUE THREAD

**Issue by emk** [jmoiron/sqlx#646]
Hello! Thank you for such an awesome Rust SQL client. We've been trying it out at work, and it looks super-promising. We'd love to use it to replace `diesel` and `tokio-postgres` in some of our open source tools.

However, many of these open source tools like [`falconeri`](https://github.com/faradayio/falconeri) and [`dbcrossbar`](https://www.dbcrossbar.org/) are shipped as statically-linked binaries using my [rust-musl-builder](https://github.com/emk/rust-musl-builder). Weirdly, `rust-musl-builder` seems to be popular for other Rust projects, with something like 740,000 downloads. So if I can figure out how to make `sqlx` work for me, it will hopefully help out some other people, too.

### The problem: Compile-time OpenSSL connections cause linker headaches when cross-compiling

In order to produce a statically-linked binary using `sqlx`, we need to compile it twice, for two different environments:

1. **The host environment.** Here, `sqlx` is compiled against GNU Libc, and Rust requires it to be a shared library that can be loaded as a "plugin" for the compiler.
2. **The target environment.** Here, `sqlx` is compiled against [`musl-libc`](https://musl.libc.org/), which is a 100% static C library that will allow a Rust binary to work on any Linux distribution with a modern kernel. This is super-useful for distributing one Linux binary that works everywhere. In this case, `sqlx` must be compiled as a static library, not a shared one.

The problem occurs because:

- `sqlx` always links against OpenSSL, in both the host and target environments.
- The Rust `openssl-sys` library can be configured to link either statically or dynamically using `OPENSSL_STATIC`, but we're forced to choose one.

### Solution 1: Fix `openssl-sys` to support both static and dynamic versions of OpenSSL at the same time

This is possible, but it's likely to be fairly complicated. The only reason anybody would ever want this is to link against OpenSSL in a macro while cross-compiling. Basically OpenSSL is native C code, and it makes everything related to cross-compiling excessively difficult.

### Solution 2: Modify `sqlx-macros` to have an `offline-only` feature

I could submit a PR that modified `sqlx-macros` to support an `offline-only` feature that _required_ an up-to-date `sqlx-data.json` file, and that had no ability to connect to the database. This would only be useful when cross-compiling. I feel like this would be fairly simple, at least compared to some of the other possible solutions.

### Solution 3: Add support for `rustls` to `sqlx`

If solution (2) seems unappealing, another option would be to allow using `sqlx` without any C dependencies at all. To do this, we could use a native Rust library like `rustls`. I've used this in other Rust projects, and it seems to be very well behaved and easy to set up.

If we had support for `rustls`, cross-compiling would magically work, even for people who just have a stock Rust install. There would be no need for tools like [rust-musl-builder](https://github.com/emk/rust-musl-builder).

### Next steps

1. Does this seem like a problem worth solving?
2. If I send you a PR solving this problem, would you be interested in merging it?
3. Which of the solution above (1, 2 or 3) seems like the best approach?

I'd be delighted to send you a PR + documentation. And I could add an `sqlx`-specific test to `rust-musl-builder` to make sure that every release of `rust-musl-builder` still supports cross-compiling with `sqlx`. This would make it very easy for Rust developers to build static Rust binaries using `sqlx`.

Once again, thank you very much for such an awesome Rust SQL interface! I really love the way it allows us to use natural SQL while still preserving the benefits of Rust's type checking.

**Comment by Mohammed90** [comment]
This a Go library. You're probably looking for the Rust library here: https://github.com/launchbadge/sqlx

**Comment by fwallacevt** [comment]
Thank you @Mohammed90

**Comment by emk** [comment]
@Mohammed90 Thank you very much! I should have remembered that there were two projects with the same name. My apologies for the mistake.
