### ISSUE TITLE
Feature request: MigrateStruct

### ISSUE THREAD

**Issue by anton7r** [jmoiron/sqlx#654]
## Backstory
From my experience writing the raw sql statements and then making them execute from a migrate function is not really a good way to manage tables, because when you modify the tables with the migrator function you have to change also your structs and sql queries which sometimes can be quite challenging.

## Feature
Since sqlx maps queries to structs it would also make sense to have an mapper that maps structs into create table commands.
This would improve developer experience quite alot and make it more easier to work with.

**Comment by arp242** [comment]
I think this would be out of scope for sqlx; but you can still write your own library to do this.
