### ISSUE TITLE
NamedExec/slice does not work with Postgres INSERT ... ON CONFLICT

### ISSUE THREAD

**Issue by cbndr** [jmoiron/sqlx#657]
First of all, thanks for this fantastic lib, Jason! It has saved me countless hours in implementing database interfaces!

I recently came across a new(?) feature which allows a NamedExec to receive a slice of structs. This works beautifully with a simple INSERT statement, generating a `VALUES (...), (...), (....) ...` list.

However, it does not work with the Postgres `INSERT INTO table VALUES (...) ON CONFLICT DO UPDATE SET column1 = :gofield1, column2 = :gofield2, ...` type of statement, as the arguments for the latter part are not "multiplied out" for all slice elements, but only appended once to the args array.

**Comment by hyperhtml** [comment]
To add, this also has issues in `mysql`
