### ISSUE TITLE
Unable to join without named select

### ISSUE THREAD

**Issue by Techassi** [jmoiron/sqlx#658]
I have these schemas (simplified for this issue):

```go
var mediaSchema = `
CREATE TABLE IF NOT EXISTS media (
	hash VARCHAR(64) PRIMARY KEY,
	title TEXT,
	plot TEXT
);`

var movieSchema = `
CREATE TABLE IF NOT EXISTS movie (
 	id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
 	belongs_to TEXT,
 	tagline TEXT,
);`
```

I have these models:

```go
type Media struct {
	Hash     string `json:"hash" db:"hash"`
	Title    string `json:"title" db:"title"`
	Plot     string `json:"plot" db:"plot"`
	Movie    `json:"movie" db:"movie"`
}

type Movie struct {
	BelongsTo   string `db:"belongs_to"`
	Tagline     string `db:"tagline"`
}
```

Trying to join these with

```go
media := []Media{}
db.Select(&media, `SELECT media.*, movie.* FROM media INNER JOIN movie ON media.hash = movie.belongs_to ORDER BY title DESC`)
```

fails with the error `missing destination name belongs_to in *[]Media`

Using a join table like 

```go
type JoinMedia struct {
	Media `db:"media"`
	Movie `db:"movie"`
}
```

fails with the same above mentioned error.

The join only works if I write my query like:

```go
db.Select(&media, `SELECT media.*, movie_, movie.belongs_to "movie.belongs_to", movie.tagline "movie.tagline" FROM media INNER JOIN movie ON media.hash = movie.belongs_to ORDER BY title DESC`)
```

It surely cannot be intended behaviour to make a join work with named selects only. Anyting I am missing here?

**Comment by Techassi** [comment]
#131 Okay apparently this isn't possible. Are there any future plans to improve the usability @jmoiron ?

**Comment by antonyc** [comment]
@Techassi you closed the ticket, did you find any solution?:)

**Comment by antonyc** [comment]
Btw isnt there an error in `SELECT media.*, movie_,` - what does column `movie_` stand for?
