### ISSUE TITLE
not support CTE？

### ISSUE THREAD

**Issue by jjjachyty** [jmoiron/sqlx#661]
``` 1064: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'as```

when i use mysql to query
```
	sql := "with tb as (select comment_id,count(comment_id) thumb_up from thumb where forum_id = 1319089984836669440 and comment_id >0 and create_by in (257049,257086) group by comment_id ) select * from tb"
err := db.Select(&comments, sql, req.ForumID, req.CommentID, req.ForumID, req.CommentID)
	if err != nil {
		return nil, err
	}
```

**Comment by Kazun3500** [comment]
Your mysql version? Mysql 5 not supports cte

**Comment by jmoiron** [comment]
Unlikely to be the fault of this package.  If you can reproduce this as failing with `sqlx` and succeeding with `database/sql` please let me know in detail what versions of everything (driver, OS, rdbms version, etc) you are using and I will try to fix it.
