### ISSUE TITLE
Update releases ?

### ISSUE THREAD

**Issue by titouanfreville** [jmoiron/sqlx#669]
While looking for merged pull requests, I noticed a good amount of them being merged since the latest releases ... Could you make a new release including those features ? Some are really nice and would lead to quite a lot of simplification in codes ... 
🙏

**Comment by rishabh-arya95** [comment]
Yes please @jmoiron, this would be really helpful for me. The bulk insert functionality is not there in release version 1.2.0.

**Comment by jeffg-hpe** [comment]
See https://github.com/jmoiron/sqlx/issues/625#issuecomment-643656247

**Comment by jmoiron** [comment]
1.3.0
