### ISSUE TITLE
Missing 1.2.1 version ?

### ISSUE THREAD

**Issue by charliemcelfresh** [jmoiron/sqlx#672]
We have this version in our go.mod

github.com/jmoiron/sqlx v1.2.1-0.20190426154859-38398a30ed85

This commit 38398a30ed85 is not tagged with v1.2.1, and v1.2.1 tag / release doesn't exist

Morever, we're looking through the docs, and we see that BindNamed is deprecated in the current docs

https://godoc.org/github.com/jmoiron/sqlx#BindNamed

- BindNamed is not deprecated in github.com/jmoiron/sqlx v1.2.1-0.20190426154859-38398a30ed85, nor does Named exist in that version
- BindNamed is not deprecated in master nor does Named exist in master

We're looking for guidance on what the latest stable commit is, thanks.

**Comment by adv0cat** [comment]
up @jmoiron

**Comment by jmoiron** [comment]
Released a new version, version 1.3.0.  I felt that there was enough added to it that it was not a patch on 1.2

docs: https://pkg.go.dev/github.com/jmoiron/sqlx@v1.3.0
