### ISSUE TITLE
NamedExec bulk insert PostgreSQL 65535 params limit

### ISSUE THREAD

**Issue by nogurenn** [jmoiron/sqlx#676]
Hello. our use case is using Go with Serverless and AWS. I understand that the params limit was thrown by the backend `pg` driver. I don't know if it's worth raising it here, but maybe someone else could make use of it. We resolved it by batching the slice to be passed to `NamedExec()`.

If this is worth documenting as behavior that sqlx will not guard against eagerly, I'll submit a doc PR soon enough.

**Comment by mirecl** [comment]
pls see https://github.com/jackc/pgx/issues/65

**Comment by nogurenn** [comment]
That checks out. Will close this. Thanks!
