### ISSUE TITLE
panic: block: expected 3 arguments (columns: id, name, action_time), got 6

### ISSUE THREAD

**Issue by jclivi** [jmoiron/sqlx#686]
tx.MustExec("INSERT INTO test.test (id,name,action_time) VALUES ($1, $2, $3),($4, $5, $6)", 
"888", "desct", "2019-12-13", 
"666","desct", "2019-12-13"
)

**Comment by jmoiron** [comment]
This seems to work in general.  The error message leads me to believe that this isn't the line that is in error, but some call to NamedExec or similar somewhere.  If you can provide a failing test or more context feel free to re-open.
