### ISSUE TITLE
How to insert array of jsontext into mysql

### ISSUE THREAD

**Issue by sandeepmachiraju** [jmoiron/sqlx#689]
Hello,

I have a requirement where I have a JSON column in the MySQL table. This should take an array of JSON dictionaries as input (as shown below). How can achieve this? 

**JSON Format:** 
`[{
		"version": 10.0,
		"autoUpdates": true
	},
	{
		"version": 9.0,
		"autoUpdates": false
	}
]`

**Code:**
```
q = `INSERT INTO my_table(jsoncol) values(:jsonvalue)`
type QueryFilter struct {
        JsonValue  []types.JSONText `db:"jsonValue"`
}
qf := QueryFilter {
  JsonValue: <JSON fomat as value mentioned above>,
}

db.NamedExecContext(ctx, q, qf)   => Here I am getting error as  "%!(EXTRA *errors.errorString=sql: converting argument $3 type: unsupported type []types.JSONText, a slice of slice)"
```

Is []types.JSONText not supported? If not, is there any workaround?  

FYI, I looked at similar issues in the 'Issues' section, but cannot figure out the solution for this problem. Please help me. Thanks.
Let me know if you need more information.

@jmoiron

**Comment by jmoiron** [comment]
JSONText allows you to store JSON somewhat transparently in a text field, it's not for json types supported by some RDBMS'.
