### ISSUE TITLE
Common interface for sqlx.Tx and sqlx.DB

### ISSUE THREAD

**Issue by defreng** [jmoiron/sqlx#692]
It would be awesome if these two types would have a common interface. This would make it very easy to write code (e.g. a repository) that doesn't care if it is working on a db or transaction object.

The only issue is that I don't have any idea for a good name for this interface :-(

**Comment by jmoiron** [comment]
They share a lot of API, but in Go anyone can define these interfaces as necessary.  I don't think I want to add more to the API;  the few interfaces that sqlx already exports are extraneous in my opinion.

**Comment by kswope** [comment]
Came here with the same question.

Right now I'm using

```
type DBTX interface {
	Get(dest interface{}, query string, args ...interface{}) error
	Exec(query string, args ...interface{}) (sql.Result, error)
}
```

But it seems adhoc, or is it a la cart?  Anyway, anybody reading this code is going to wonder what going on.
