### ISSUE TITLE
sql: expected 0 arguments, got 5: Get error when running stdin copy in a statement 

### ISSUE THREAD

**Issue by yang-f** [jmoiron/sqlx#716]
driver:pgx
```golang
tx ,err := dbconn.Beginx()
if err != nil{
        return err
}

stmt, err := tx.Preparex(`COPY "public"."testtable" ("time", "tagid", "c1", "c2", "c3") FROM STDIN`))
if err != nil {
	return err
}
// len(args) == 5
// Get error:  sql: expected 0 arguments, got 5
_, err = stmt.Exec(args...)
if err != nil {
	return err
}
```

**Comment by britishboop** [comment]
Did you find a solution for this? I'm running into the same issue

**Comment by yang-f** [comment]
> Did you find a solution for this? I'm running into the same issue

https://github.com/jackc/pgx/issues/485

**Comment by britishboop** [comment]
> > Did you find a solution for this? I'm running into the same issue
> 
> [jackc/pgx#485](https://github.com/jackc/pgx/issues/485)

Ah, that explains it, thanks!

**Comment by rianrais** [comment]
Hi I checked the solution but still don't understand what we are supposed to do, any help would be appreciated.
