### ISSUE TITLE
please publicly document the "-" tag

### ISSUE THREAD

**Issue by rbastic** [jmoiron/sqlx#725]
From line 377 in reflectx/reflect.go, we see:

            // if the name is "-", disabled via a tag, skip it

It would be great if we could document this publicly. Would it be possible to fire off a PR to resolve this? Open to thoughts/suggestions.

**Comment by gurza** [comment]
The dash tag isn't sqlx specific construction. It's standard Go construction. In every tag, as in `db:"-"` or in `json:"-"`, the dash means "ignore". So it looks there is no point in further documenting any standard constructs.

@rbastic what do you think?

**Comment by rbastic** [comment]
That is a fair point!
