### ISSUE TITLE
batch update err 

### ISSUE THREAD

**Issue by ChanKunggc** [jmoiron/sqlx#730]
![image](https://user-images.githubusercontent.com/56463479/115977743-59d52c00-a5ad-11eb-9897-c801bbff76a9.png)
this are  postgresql err log
![image](https://user-images.githubusercontent.com/56463479/115977751-6a85a200-a5ad-11eb-9455-79be0b1f97ac.png)

**Comment by QuangTung97** [comment]
Maybe the line `db.Rebind(query)`
should be `query = db.Rebind(query)`.
Because the function `db.Rebind` does not change the string in place.
Postgres driver's bindvar type is, for example: $1 $2, not question mark.

**Comment by ChanKunggc** [comment]
> Maybe the line `db.Rebind(query)`
> should be `query = db.Rebind(query)`.
> Because the function `db.Rebind` does not change the string in place.
> Postgres driver's bindvar type is, for example: $1 $2, not question mark.

You are right ,thank you so much !
