### ISSUE TITLE
Code runs without any errors but nothing is inserted into the table.

### ISSUE THREAD

**Issue by timuckun** [jmoiron/sqlx#764]
I have an upsert query like this

INSERT INTO table (.......) 
VALUES (:field1,:field2, ....)
ON CONFLICT (field1, field2) DO NOTHING

I create a slice of structs where the members have the same name as fields

I then run this

```go
rows, err := db.NamedQuery(upsertQuery, buffer)
				if err != nil {
					pp.Println("wrote batch")
				} else {
					log.Fatal(err)
				}
```

It outputs the "wrote batch" line but there is nothing in the database.

I also did NamedExec. The result is nil, no errors, nothing in the table

**Comment by Akaame** [comment]
If you still have not solved this issue please send a minimal reproducible example of your problem.

Off-topic
> ON CONFLICT (field1, field2) DO NOTHING

this does not seem like "upsert" behavior. 

Regards.
