### ISSUE TITLE
NamedQuery but return *Row instead of *Rows

### ISSUE THREAD

**Issue by loganphillips792** [jmoiron/sqlx#766]
NamedQuery looks like: `func (db *DB) NamedQuery(query string, arg interface{}) (*Rows, error)`

The named bindvars are very convenient to work with, but there has been a number of times I have wanted the functionality of NamedQuery, but have it return `*Row ` instead of `*Rows`.

I think the addition of a 'NamedQueryRow' which looks like:

`func (db *DB) NamedQueryRow(query string, arg interface{}) (*Row, error)` could be useful. 

Any thoughts on this? I am relatively new to using this library so curious to see what others think.

Thanks!

**Comment by gnuletik** [comment]
Hi !
I'm also looking for this feature.
Did you find a solution ?
Thanks!

**Comment by loganphillips792** [comment]
Hey @gnuletik, sorry for replying so late. But I did not find a solution to this. I just ended up closing the issue because I didn't get any feedback on it. Are you still looking for this feature?

**Comment by gnuletik** [comment]
@loganphillips792 Thanks for the reply!

Yes, still looking for this feature :)
That could be a nice improvement I think!

**Comment by Hendrikto** [comment]
Any chance this feature will be reconsidered? It has been requested for 10 years, and I still would like to see it implemented.

* 2014: #102
* 2016: #250
* 2016: #256
* 2021: #766 (this issue)
* 2024: I would like this feature as well.
