### ISSUE TITLE
Injection of SQL parameters seems to fail on MySQL

### ISSUE THREAD

**Issue by gomapsdev** [jmoiron/sqlx#78]
MySQL Ver 14.14 Distrib 5.6.19, for osx10.9 (x86_64) using  EditLine wrapper

``` Go
tmpUser := User{}
err := db.DB.Get(&tmpUser, "SELECT * FROM user WHERE email=$1", "jack@frost.com")
```

err = "Error 1054: Unknown column '$1' in 'where clause'"

This works correctly if I do this:

``` Go
tmpUser := User{}
err := db.DB.Get(&tmpUser, "SELECT * FROM user WHERE email=\"jack@frost.com\"")
```

err = nil

Any ideas?

**Comment by divan** [comment]
Hit this problem as well. My previous experience with database/sql was using mysql driver only, so when I read the Usage section of Readme and saw "$1", I decided that it's sqlx-specific and I should use it. 

Probably worth to point out explicitly that example is for postgres only, and, perhaps, add examples for mysql driver also, as it seems to be quite popular.

**Comment by jmoiron** [comment]
This is covered in the [documentation](http://jmoiron.github.io/sqlx/#bindvars)

**Comment by divan** [comment]
Great! Wouldn't it be nice to copy short excerpt of bindvars to the README as well?
I usually don't read documentation ~~at all~~ if everything is clear from README, which is extensive in this case.

**Comment by errogaht** [comment]
Can you describe why it must be normal that every database uses its own params placeholder?
Looks really weird, why not use $ or ? always?!

**Comment by Daltonoverhanging** [comment]
@gomapsdev https://stackdev.space/questions/exploring-the-power-of-mysql-in-manipulating-strings-with
