### ISSUE TITLE
sqlx + pgx + sslmode=require

### ISSUE THREAD

**Issue by ev94** [jmoiron/sqlx#792]
Hi,

Thx for the great work.
We are currently migrating from sqlx + pq   to   sqlx + pgx.
We are using sslmode=require&sslrootcert=xxxxxx.
Everything works fine with sqlx + pq but with pgx, we are not able to connect to our db. We have the following error message:
`: failed to write startup message (tls: either ServerName or InsecureSkipVerify must be specified in the tls.Config)`

How to access to pgx tls.Config? It seems to be hidden by sqlx.

Thx
Emmanuel

**Comment by VivienLambert** [comment]
Hi

You can try using other ssl modes like verify-full (more secured) or verify-ca (a bit like require). It may work

Have a good day

**Comment by ev94** [comment]
It works!
