### ISSUE TITLE
Does this project stop maintain?

### ISSUE THREAD

**Issue by drakejin** [jmoiron/sqlx#793]
I'm very careful to ask to maintainers.. There are no comments about old P.R and Issues. Should I fork and use this sqlx...? 

I need #791 #780

**Comment by rowanseymour** [comment]
Wondering the same as we need https://github.com/jmoiron/sqlx/pull/715. Anyone maintaining a fork now?

**Comment by ehasnain** [comment]
> Wondering the same as we need #715. Anyone maintaining a fork now?

Hi @rowanseymour.  Well, I have forked the library and updated the lib/pq package dependency to the last released version. We can maybe collaborate and maintain my Fork.
Feel free to suggest something more sustainable. :)

**Comment by dlsniper** [comment]
Hello! Sorry for the delay in replying. @ardan-bkennedy and I recently stepped in to help maintain the project.
We are in the process of triaging all the opened PRs and then issues, and we plan to address outstanding issues and upgrade the library to support generics and new Go versions, among other things.
