### ISSUE TITLE
MapScan should accept maps of different types

### ISSUE THREAD

**Issue by jmoiron** [jmoiron/sqlx#80]
MapScan currently takes `map[string]interface{}` but it should take `interface{}`, require it to be a map with a keytype of string, but otherwise allow it to scan into things of different types, eg `map[string]int{}`

The documentation also has to be fixed, it doesn't do any kind of string coercion anymore, it just scans to `interface{}` (which will change;  it'l just scan to whatever your map value type is)

**Comment by c4milo** [comment]
I'm curious, why does MapScan always return []uint8 types for text fields? I've been having to do a type assertion to []uint8 as well as a cast to string. Could it be the driver?

Ex: 

```go
g.Code = string(row["code"].([]uint8))
```

**Comment by donileo** [comment]
Great question. I meant to ask this a long time ago
