### ISSUE TITLE
SQLite - backup/restore error

### ISSUE THREAD

**Issue by kassane** [jmoiron/sqlx#816]
I'm having problem executing SQLite command.

```go
_, err := database.Exec(".backup database.bak")
...
_, err := database.Exec(".restore database.bak")
```

**Output**:
```bash
near \".\": syntax error
```

**Comment by mohammed90** [comment]
The `.backup` and `.restore` commands are offerings of the SQLite shell, not of its SQL dialect. For backup api, use the dedicated funcs from github.com/mattn/go-sqlite3 package.

**Comment by kassane** [comment]
> The `.backup` and `.restore` commands are offerings of the SQLite shell, not of its SQL dialect.

lol so that was it. OK! I had encountered this problem in the college project.

> For backup api, use the dedicated funcs from github.com/mattn/go-sqlite3 package.

We're avoiding more dependencies so I think trying to run processes directly helps.

**Comment by mohammed90** [comment]
> We're avoiding more dependencies so I think trying to run processes directly helps.

If you're using SQLite, chances are you're already using mattn/go-sqlite3 or modernc.org/sqlite. They are the defacto standard SQLite drivers in Go, and sqlx doesn't work with SQLite without either of them.

**Comment by kassane** [comment]
> > We're avoiding more dependencies so I think trying to run processes directly helps.
> 
> If you're using SQLite, chances are you're already using mattn/go-sqlite3 or modernc.org/sqlite. They are the defacto standard SQLite drivers in Go, and sqlx doesn't work with SQLite without either of them.

Nice tip. thx!
