### ISSUE TITLE
unexpected TIME_WAIT  on database server after close connection

### ISSUE THREAD

**Issue by superceix** [jmoiron/sqlx#823]
golang client: server1 
db: server2

my program connect to database server1, and close after query. sometimes, TIME_WAIT appear on  the database server. 

this is unexpected. how can i solve it.

this is my test code:
```

func query() {
	conn, err := sqlx.Connect("mysql", "root:root@(server1_ip:3306)/?charset=utf8&timeout=2s")
	if err != nil {
		fmt.Println("connect error")
		return
	}
	conn.SetMaxOpenConns(1)
	conn.SetMaxIdleConns(10)

	defer conn.Close()

	var tmp = 0

	err = conn.Get(&tmp, "select 1")
	if err != nil {
		fmt.Println("select error")
	}
}

func main() {
	for {
		fmt.Println("start query")
		query()
		time.Sleep(time.Millisecond * 200)
	}
}

```

**Comment by jakoblorz** [comment]
> On an high frequent application on the web which opens a mysql-connection per request, a high amount of TIME_WAIT connections is expectable. There is nothing wrong with it.

https://stackoverflow.com/questions/5062839/mysql-time-wait-too-many-connections-problem#:~:text=If%20the%20client%20closes%20the,packets%20from%20a%20former%20connection.

**Comment by superceix** [comment]
> 
get it
