### ISSUE TITLE
Retrieve ID from insert to DB

### ISSUE THREAD

**Issue by luiscvega** [jmoiron/sqlx#83]
Hi!

I have this insert into the database:

```
user := new(User)
res, err := db.NamedExec("INSERT INTO users (email) VALUES (:email) RETURNING id", user)
```

And I'd like to get the ID of that record. I believe I'm using the `RETURNING id` incorrectly. Is this the correct way to do it via `db.NamedExec`? If not, what are the proper ways to do so?

Thanks!
@luiscvega

**Comment by dontogbe** [comment]
@jmoiron Hi
When the insert fails you still get the id returned. err is also nil.
How can you tell if the insert was not successful (e.g. due to a foreign key constraint)?

**Comment by karanthakker47** [comment]
@jmoiron I am running into the same issue as @dontogbe - I am using NamedQuery() to insert values into a table such that a foreign key constraint is violated.

However, the error returned by NamedQuery() is nil, and the issue can only be caught when the transaction is being committed.

Is there a way for us to catch this error sooner?

**Comment by juroberttyb** [comment]
As a reminder, for people using this method, don't forget to add
```
rows.Close()
```
to the end of the query before continuing, otherwise there would be idle sql connections hanging in the database, which may cause database unreachable.


> Hi Luis,
> 
> Try using `NamedQuery` instead and scanning the resulting rows:
> 
> ```go
> var id int
> var user User
> rows, err := db.NamedQuery("INSERT INTO users (email) VALUES (:email) RETURNING id", user)
> // handle err
> if rows.Next() {
>     rows.Scan(&id)
> }
> ```
> 
> You could also use a prepared named statement which you can then use `Get` with.
> 
> Hope this helps!
