### ISSUE TITLE
Ability to change the `db` tagname

### ISSUE THREAD

**Issue by thaonx** [jmoiron/sqlx#863]
I want to change the default `db` tag to `json` as the entities are genereted from protobuf.
```
type User struct {
    UserName `json:"user_name"`
}
```
However, the `mpr` currently is unexported and there is no function that allows to set the reflectx.Maper.
https://github.com/jmoiron/sqlx/blob/master/sqlx.go#L32
```
package sqlx
...
var mpr *reflectx.Mapper
```

**Comment by dgroux** [comment]
@thaonx 

Here you go:

```
import(
    "github.com/jmoiron/sqlx"
    "github.com/jmoiron/sqlx/reflectx"
    "github.com/iancoleman/strcase"
)

conn = sqlx.NewDb(db, "mysql")
conn.Mapper = reflectx.NewMapperFunc("json", strcase.ToSnake)
```

**Comment by thaonx** [comment]
thanks @dgroux
