### ISSUE TITLE
Why ExecerContext only can be used in "MustExecContext"

### ISSUE THREAD

**Issue by zyf-source** [jmoiron/sqlx#871]
I want to use Execer, but I don't want to use panic. But I found sqlx only have the MustExecContext method.
If there is a error, it would panic

**Comment by gurza** [comment]
`MustExecContext()` is a method in sqlx which will panic if there's an error. However, sqlx also provides the `ExecContext()` method, which will return an error instead of panicking.

```golang
res, err := db.ExecContext(context.TODO(), "INSERT INTO users(name) VALUES(?)", "John Doe")
if err != nil {
    // Handle error here.
}
```

Generally speaking, in golang, the implementation of a method with the prefix Must looks like this

```golang
func (s *Service) MustFuncContext(ctx context.Context, arg interface{}) (*Result, error) {
	res, err := s.FuncContext(ctx, arg)
	if err != nil {
		panic(err)
	}
	return res, nil
}
```

**Comment by zyf-source** [comment]
> `MustExecContext()` is a method in sqlx which will panic if there's an error. However, sqlx also provides the `ExecContext()` method, which will return an error instead of panicking.
> 
> ```go
> res, err := db.ExecContext(context.TODO(), "INSERT INTO users(name) VALUES(?)", "John Doe")
> if err != nil {
>     // Handle error here.
> }
> ```
> 
> Generally speaking, in golang, the implementation of a method with the prefix Must looks like this
> 
> ```go
> func (s *Service) MustFuncContext(ctx context.Context, arg interface{}) (*Result, error) {
> 	res, err := s.FuncContext(ctx, arg)
> 	if err != nil {
> 		panic(err)
> 	}
> 	return res, nil
> }
> ```

Thanks. sqlx provides MustExecContext, Its signature is as follows
`func MustExecContext(ctx context.Context, e ExecerContext, query string, args ...interface{}) sql.Result {
	res, err := e.ExecContext(ctx, query, args...)
	if err != nil {
		panic(err)
	}
	return res
}`
It takes ExecerContext as parameter, ExecerContext can be DB/Stmt/Tx..., what i need is a function **ExecContext** like this, not db.ExecContext/tx.ExecContext.
`func ExecContext(ctx context.Context, e ExecerContext, query string, args ...interface{}) (sql.Result, error) {
	return e.ExecContext(ctx, query, args...)
}`

What puzzles me is that sqlx provides MustExecerContext only.

**Comment by zyf-source** [comment]
> `MustExecContext()` is a method in sqlx which will panic if there's an error. However, sqlx also provides the `ExecContext()` method, which will return an error instead of panicking.
> 
> ```go
> res, err := db.ExecContext(context.TODO(), "INSERT INTO users(name) VALUES(?)", "John Doe")
> if err != nil {
>     // Handle error here.
> }
> ```
> 
> Generally speaking, in golang, the implementation of a method with the prefix Must looks like this
> 
> ```go
> func (s *Service) MustFuncContext(ctx context.Context, arg interface{}) (*Result, error) {
> 	res, err := s.FuncContext(ctx, arg)
> 	if err != nil {
> 		panic(err)
> 	}
> 	return res, nil
> }
> ```



Thanks for the reply, sqlx provides MustExecContext, Its signature is as follows
```
func MustExecContext(ctx context.Context, e ExecerContext, query string, args ...interface{}) sql.Result {
	res, err := e.ExecContext(ctx, query, args...)
	if err != nil {
		panic(err)
	}
	return res
}
```
It takes ExecerContext as parameter, ExecerContext can be DB/Stmt/Tx..., what i need is a method ExecContext like this, not db.ExecContext/tx.ExecContext.
```
func ExecContext(ctx context.Context, e sqlx.ExecerContext, query string, args ...interface{}) (sql.Result, error) {
	return e.ExecContext(ctx, query, args...)
}
```
What puzzles me is that sqlx provides MustExecContext method only.

**Comment by gurza** [comment]
The method `MustExecContext()` wraps a call to `e.ExecContext()`, where e is an instance of type `ExecerContext`. To execute a query using the method `ExecContext()`, a connection to the database is required, which is why this method is implemented in the DB/Stmt/Tx... structures.

To make a call to `MustExecContext()`, you need to have an instance of `ExecerContext`. Could you please explain why you cannot just call the method of the `ExecerContext` instance? Without `MustExecContext()` wrap.

**Comment by zyf-source** [comment]
> The method `MustExecContext()` wraps a call to `e.ExecContext()`, where e is an instance of type `ExecerContext`. To execute a query using the method `ExecContext()`, a connection to the database is required, which is why this method is implemented in the DB/Stmt/Tx... structures.
> 
> To make a call to `MustExecContext()`, you need to have an instance of `ExecerContext`. Could you please explain why you cannot just call the method of the `ExecerContext` instance? Without `MustExecContext()` wrap.

My application has two layers， the repository layer just like

```
type TestRepo struct {
}

func (r *TestRepo) Create(ctx context.Context, execer sqlx.ExecerContext, test *entity.TestEntity) error {
	ds := goqu.Dialect("mysql").Insert("xxx").Rows(test)
	insertSQL, args, err := ds.Prepared(true).ToSQL()
	if err != nil {
	}
         // if sqlx provides ExecContext method as above
	_, err = sqlx.ExecContext(ctx, execer, insertSQL, args...)
	if err != nil {
	}
	return err
}
```
When this method needs to be called, depending on the situation, the **ExecerContext** can be a sqlx.Tx if need to open a transaction, also can be sqlx.DB when unnecessary.
