### ISSUE TITLE
Feature Request - Custom Log Printing and Hook Mechanism

### ISSUE THREAD

**Issue by suiriass** [jmoiron/sqlx#873]
Hello,

While using the sqlx ORM framework, I would like to request a couple of additional features.

Feature Requests:

Custom log printing: It would be great if the framework could support custom log printing, allowing users to define their own log output format and destination.

Hooks: It would be helpful to have a hook mechanism in the framework, enabling users to execute custom code before or after certain actions, such as executing a query or committing a transaction.

I would appreciate it if you could consider implementing the requested features. Thank you for your time and effort in developing and maintaining this great ORM framework.

Best regards,

**Comment by gurza** [comment]
The `sqlx` package is good for its simplicity.

To implement a **hook mechanism** in `sqlx`, you will need to create a custom wrapper that embeds `sqlx.DB`, `sqlx.Tx`, `sqlx.Stmt`, etc., and overrides the methods where you want to insert pre- and post-hooks.

```golang
type WrapDB struct {
	*sqlx.DB
}

func (db * WrapDB) Exec(query string, args ...interface{}) (sql.Result, error) {
	log.Println("Pre-hook for Exec.")

	result, err := db.DB.Exec(query, args...)
	if err != nil {
		log.Println("Post-hook for Exec with error.")
		return nil, err
	}

	log.Println("Post-hook for Exec.")

	return result, err
}
```

To support custom logging in `sqlx`, one approach could be creating a logging interface and including it in the same custom wrapper as described in the hook mechanism above. 

```golang
type Logger interface {
	Printf(format string, v ...interface{})
	// ...
}

type WrapDB struct {
	*sqlx.DB
	Logger Logger
}

func (db *MyDB) Exec(query string, args ...interface{}) (sql.Result, error) {
	db.Logger.Printf("Pre-hook for Exec: %s", query)
	// ...
}
```

**Comment by gurza** [comment]
@suiriass sqlx is not a framework, it is a set of useful extensions for the database package from the standard library. In the comment above, I showed how you can easily solve your request. If you have no more questions, please close this issue.

**Comment by suiriass** [comment]
Thanks, yes, I was able to solve it myself, which required wrapping each exec method, and frameworks such as gorm could easily solve it.

**Comment by suiriass** [comment]
> @suiriass sqlx is not a framework, it is a set of useful extensions for the database package from the standard library. In the comment above, I showed how you can easily solve your request. If you have no more questions, please close this issue.

Thanks, yes, I was able to solve it myself, which required wrapping each exec method, and frameworks such as gorm could easily solve it.
