### ISSUE TITLE
Is project dead?

### ISSUE THREAD

**Issue by henryx** [jmoiron/sqlx#878]
Last commit was on April 2022. After this date, nothing changed in the evolution of the project. So, as of today, project is to be considered still alive?

**Comment by uvulpos** [comment]
https://www.reddit.com/r/golang/comments/l43wn7/comment/gkm42xz/?utm_source=share&utm_medium=web2x&context=3

> In my opinion, it's feature complete. There's one major feature I would like to add but can't come up with a good design for. The amount of outstanding issues and PRs is due to my inability to really engage with these with the care I would like, rather than an indicator of problems in the behaviour of the library.

I would say this is the answer to it. Which is sad because there are also still bugs in this code 🙁

**Comment by BenKnigge** [comment]
I've forked it for my own needs but have started merging some of the existing pr's into my fork. If either of your would be interested in either creating a fork or helping me with mine let me know. https://github.com/BenKnigge/sqly

**Comment by uvulpos** [comment]
@BenKnigge I would appreciate it to maintain the project as https://github.com/go-sqlx/sqlx. However, there is an interesting issue in the go src repo speaking about implementing a native solution. This would make sqlx then obsolete. https://github.com/golang/go/issues/61637

**Comment by BenKnigge** [comment]
@uvulpos it looks like you have already started to do what I'm just starting to do. A native solution would be nice but sqlx also has named parameters as some other features not mentioned.

**Comment by uvulpos** [comment]
Yes, I did not use every feature of this library, so it needs to be added now. But we could merge our work together if you'd like to. I invited you as a maintainer to the project if you are interested :)

**Comment by BenKnigge** [comment]
I've already made a pr to your fork and asked a question in the discussion.

**Comment by PaluMacil** [comment]
No need for a fork. People that used sqlx should mostly use [scany](https://github.com/georgysavva/scany) now. It's mature, active, and if you use Postgres you can even use the native interface and types, though it supports database/sql for everyone else as well.

**Comment by nielskrijger** [comment]
Scany appears to be quite low-maintenance; it's months between commits.

**Comment by dlsniper** [comment]
Hello! Sorry for the delay in replying. @ardan-bkennedy and I recently stepped in to help maintain the project.
We are in the process of triaging all the opened PRs and then issues, and we plan to address outstanding issues and upgrade the library to support generics and new Go versions, among other things.
