### ISSUE TITLE
Has this project been abandoned? 

### ISSUE THREAD

**Issue by BenKnigge** [jmoiron/sqlx#883]
The last commit  was over a year ago and their are 63 open pr's. It's still fairly popular. @jmoiron If your willing, could you allow someone else to to continue to maintain you're wonderful project?

**Comment by bknigge-sightline** [comment]
@jmoiron if you would like to distance yourself from the project, could you archive it and possibly link to a fork that is being maintained?

**Comment by BenKnigge** [comment]
For now I'm going through some of the existing pr's and merging them into my fork at https://github.com/BenKnigge/sqly 

If this project comes back to life at some point I'll delete that or point it back here.

**Comment by PaluMacil** [comment]
@bknigge-sightline and @BenKnigge  People that used sqlx should mostly use [scany](https://github.com/georgysavva/scany) now. It's mature, active, and if you use Postgres you can even use the native interface and types, though it supports database/sql for everyone else as well.

**Comment by nielskrijger** [comment]
Scany appears to be quite low-maintenance too.

**Comment by PaluMacil** [comment]
@nielskrijger If you look at the comments and pull requests, I think it's fair to call it active. If there aren't a lot of commits, I figure the way to see if something is active as to see if there are outstanding problems or solved problems where the solution isn't giving triaged

**Comment by nielskrijger** [comment]
Might be worth pointing out, that if you use PostgreSQL you could also consider using pgx which support struct scanning since 5.1.0: https://pkg.go.dev/github.com/jackc/pgx/v5#RowToStructByName

**Comment by PaluMacil** [comment]
@nielskrijger scany supports a lot more than pgx though, so that's why I mentioned it as a sqlx replacement, not a pgx replacement.

**Comment by dlsniper** [comment]
Hello! Sorry for the delay in replying. @ardan-bkennedy and I recently stepped in to help maintain the project.
We are in the process of triaging all the opened PRs and then issues, and we plan to address outstanding issues and upgrade the library to support generics and new Go versions, among other things.
