### ISSUE TITLE
escape `::` as `:` in named queries

### ISSUE THREAD

**Issue by jmoiron** [jmoiron/sqlx#91]
Discussed a bit at length in #85, it is currently impossible to write queries that should contain a literal `:`.  The named query parsing should be modified to allow for that by allowing the `::` escape to mean a single `:` in the result query.  This follows from the sql standard's `''` to escape `'` inside string literals.

This will be unlikely to have much impact on current uses of sqlx;  there is no valid use of `::` currently for named statements.

**Comment by oreqizer** [comment]
can this be documented, please? I've been battling two hours with this issue and haven't found it documented anywhere

**Comment by dhduvall** [comment]
In particular, I needed to use this in order to escape the colons in a named query that included a cast:

    VALUES (':structmember'::::bytea)

I'm not sure if I would have seen the documentation before figuring this out, but I agree that having something in the illustrated guide, at least, would be useful.
