### ISSUE TITLE
Tag new version for dependency security updates

### ISSUE THREAD

**Issue by seanhagen** [jmoiron/sqlx#923]
The last version ( v1.3.5 ) was tagged in 2022. A new version needs to be tagged so that folks ( such as myself ) can update our `go.mod` files to stop getting warnings about security vulnerabilities in package versions no longer referenced in this package's `go.mod` file. 

For example: in the latest tag v1.3.5, the version of `go-sqlite3` being used is [v1.14.6](https://github.com/jmoiron/sqlx/blob/v1.3.5/go.mod#L8C30-L8C37). In the `go.mod` file on the master branch the version is [v1.14.22](v1.14.22) ( enough to get security scanners like Snyk to stop complaining ).

Can we get a v1.3.6 tagged to master?

**Comment by dlsniper** [comment]
Hi @seanhagen. Thanks for the issue. Sorry, it took a little longer to get this done. We'll keep the dependencies updated more frequently in the future.
